### ISSUE TITLE
Podcast Settings: Play Speed changes when switching podcast's settings

### ISSUE THREAD

**Issue by pocketcasts** [Automattic/pocket-casts-ios#1]
### Steps to reproduce the behavior

- Open a podcast
- Open podcast settings
- Tap on playback effects 
- Switch “Custom for this podcast” on
- Increase play speed to 1,5
- Leave podcast settings an podcast
- Open another podcast’s settings
- Go back to the first podcast’s settings —> play speed is not 1,5 anymore, but 1,1 (you can increase the speed by 0,1 each time by repeating the procedure)

### Additional information

it doesn't seem to happen on iOS 15 (only iOS 14).

**Comment by rviljoen** [comment]
I was able to reproduce this on v7.26 running on iOS 16.1.1 as well. For me, the delta is not always 0,1 and it goes both up and down in value.
