### ISSUE TITLE
File Size Sometimes Showing As "0 Bytes"

### ISSUE THREAD

**Issue by igotdes** [Automattic/pocket-casts-ios#1044]
### Expected behavior

An episode's details should show the correct file size.

### Actual behavior

In some cases—although we haven't figured out a pattern yet—an episode's details only show "0 bytes" for an episode's file size. Tapping "0 bytes" will initiate the download for the episode. Once the download is completed, the correct file size shows up.

### Steps to reproduce the behavior

We can test with the following episode: https://pca.st/exftsotu

1. View the episode's details
2. Sometimes, the file size will show up as "0 bytes":

![67eebb23-7a3f-4667-b26f-b313e613eb01_image](https://github.com/Automattic/pocket-casts-ios/assets/74066241/5df1e4fc-800e-4e0c-8a30-9c89cf957a0f)

3. Tap "0 bytes" and the app will download the episode.
4. Once the download completes, the correct file size shows up.

##### Tested on [device], iOS [version], Pocket Casts [version]

- iPhone SE 2022
- iOS 16.5.1
- Pocket Casts 7.45.0.2

**Comment by EmmelineKB** [comment]
The file size figures are taken from the “length” listed in the feed - for any episodes showing 0, the length is zero in the feed:

`<enclosure url="https://pdst.fm/e/chtbl.com/track/18BF3D/traffic.megaphone.fm/IWTYB5494925374.mp3?updated=1692064471" length="0" type="audio/mpeg"/>`

Once the episode is downloaded, then the app knows the size.


This also means that sometimes the size/length of an episode that is listed in the feed, and therefore the app, can change once it’s downloaded and the true size is known. Here is an example where the length is listed:

`<enclosure url="https://chtbl.com/track/5899E/podtrac.com/pts/redirect.mp3/traffic.omny.fm/d/clips/e73c998e-6e60-432f-8610-ae210140c5b1/0c6fc944-eaa5-4022-8e77-ae3300346d76/be65e87e-12cc-4e4e-8e1b-b04a0074a9e2/audio.mp3?utm_source=Podcast&in_playlist=45a735b6-e1b8-49f9-a595-ae3300346d84" length="65070949" type="audio/mpeg"/>`

This means that 65.1 MB is shown in-app. Once downloaded, this episode's size is actually 71.6 MB.

**Comment by joashrajin** [comment]
+1 in 7099707-zd-a8c - `length` was set to 0

**Comment by leandroalonso** [comment]
I think we should hide the "0 bytes" string if we don't know the size. This is probably a better approach.

**Comment by salConigliaro** [comment]
Hiding the "0 bytes" string leaves an empty spot. Maybe adding "TBD" (or something similar) might look ok? Or just add the existing "Download" title to the label?

<img width="354" alt="Screenshot 2024-02-01 at 12 49 43 PM" src="https://github.com/Automattic/pocket-casts-ios/assets/881441/cca1f5f2-7708-4235-85e6-51cc0a3e2203">
<br><br>
<img width="356" alt="Screenshot 2024-02-01 at 12 48 09 PM" src="https://github.com/Automattic/pocket-casts-ios/assets/881441/48ed7475-c714-46b5-945d-5f9fcce547c8">

**Comment by bikrrr** [comment]
I recommend showing **Download** as the label when the episode size is unknown (aka, "0 bytes"). This maintains visual balance across the four actions and is what Pocket Casts on Android uses in the same situation:

![PocketCastsAndroidDownloadButton0Bytes](https://github.com/Automattic/pocket-casts-ios/assets/2607653/51d6f342-c06f-4c3f-a205-a5e7e01c0ef8)

**Comment by bjtitus** [comment]
Fixed in #1428
