### ISSUE TITLE
Bookmarks: Final Touches

### ISSUE THREAD

**Issue by emilylaguna** [Automattic/pocket-casts-ios#1061]
### What's New
- [x] Add What's New for Bookmarks: https://github.com/Automattic/pocket-casts-ios/pull/1172

### Bookmark Creation
- [x] When creating a bookmark that is at the same time as another bookmark, display the edit title screen: https://github.com/Automattic/pocket-casts-ios/pull/1068

### Bookmark Play
- [x] Stay on the same screen when playing a bookmark: https://github.com/Automattic/pocket-casts-ios/pull/1069

### Player
- [x] Rename the Show Notes tab to 'Details': https://github.com/Automattic/pocket-casts-ios/pull/1067
- [x] Update the tab style to [reflect the updated style in the designs](https://www.figma.com/file/Io7PCz1H1hmOgEE9eljoYW/Bookmarks?type=design&node-id=2032-52290&mode=dev): https://github.com/Automattic/pocket-casts-ios/pull/1067
- [x] Increase the tab switch transition speed: https://github.com/Automattic/pocket-casts-ios/pull/1067
- [x] When bookmarks are enabled, have the player action appear between mark as played and archived in the more menu: https://github.com/Automattic/pocket-casts-ios/pull/1069

### Upgrade Screen
- [x] Change the upgrade button title to be: https://github.com/Automattic/pocket-casts-ios/pull/1069
   - If the tier has a free trial: `Start Free Trial`
   - If not: `Upgrade to X`
      - Where X is name of the tier (Plus, or Patron)

### Bookmark Sorting
- [x] Store the sort option on a "per list" basis where each bookmark lists option is saved separately: https://github.com/Automattic/pocket-casts-ios/pull/1069

### Edit Title Screen
- [x] Button color can display incorrectly for some podcasts (Ie: The Pocket Cast): https://github.com/Automattic/pocket-casts-ios/pull/1066
- [x] When editing a bookmark change the save button title to 'Change Title': https://github.com/Automattic/pocket-casts-ios/pull/1066

### User Files
- [x] When creating a bookmark with the files list open, the bookmark indicator doesn't display unless you reopen the view: https://github.com/Automattic/pocket-casts-ios/pull/1065

### Headphone Controls
- [x] Add the confirmation tone: https://github.com/Automattic/pocket-casts-ios/pull/1076
- [x] Show all the available options for next and prev: https://github.com/Automattic/pocket-casts-ios/pull/1069

### Syncing
- [x] Bookmarks created from iOS won't incrementally sync to Android: https://github.com/Automattic/pocket-casts-ios/pull/1062

**Comment by rviljoen** [comment]
@emilylaguna I tested the bookmarks functionality and it works very well! This will be a very popular feature for sure. Well done 👏🏻

One useful addition could be to provide a full list of bookmarks somewhere, across all podcasts. Maybe something similar to the starred episodes list under the profile tab? The main use case for me is to bookmark ideas that I want to return to process further when I am in front of my PC. Being able to access these in a single place would be great. For now I am looking at Listening History for episodes with the bookmark icon (another nice touch BTW!)

**Comment by emilylaguna** [comment]
@rviljoen Thank you so much for your kind words ❤️ !!

> One useful addition could be to provide a full list of bookmarks somewhere, across all podcasts. Maybe something similar to the starred episodes list under the profile tab?

I agree, we have this planned for a future update, stay tuned ;)

**Comment by rviljoen** [comment]
@emilylaguna Another suggestion to add some polish to this feature. Introduce a setting to prevent downloaded bookmarked episodes from being archived, similar to what is available for starred episodes. The motivation would be similar than for starred episodes, i.e. when bookmarked (or starred) the likelihood of returning to that episode after completion to revisit the bookmark is high.  To work around this for now, I have set the archive for played episodes to 24 hours but ideally, I want played episodes to be archived immediately, with the exception of bookmarked episodes. Makes sense?

![image](https://github.com/Automattic/pocket-casts-ios/assets/25402814/fc1e1630-338f-4f50-8b8e-1c2ed1e426c4)
