### ISSUE TITLE
Play / Pause doesn't work on the Now Playing widget with user-added files

### ISSUE THREAD

**Issue by EmmelineKB** [Automattic/pocket-casts-ios#1114]
### Description

When a user-added file is in the player, tapping the play or pause buttons in the Now Playing widget has no effect. 

### Step-by-step reproduction instructions

1. Start playing a user-added file
2. Exit the app and tap pause on the Now Playing widget
3. The file does not pause

This is also the same if you are trying to play the file via the widget:

1. Have a user-added file in the player
2. Exit the app and tap play on the Now Playing widget
3. The file does not play

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

iPhone 14 Pro, iOS 17.0, app version 7.47.0.4

**Comment by joashrajin** [comment]
6998434-zd-a8c

**Comment by rviljoen** [comment]
@leandroalonso I think this one can be closed?

**Comment by leandroalonso** [comment]
Yup! Thanks
