### ISSUE TITLE
The player tab bar fade can be the wrong color when changing the episode

### ISSUE THREAD

**Issue by emilylaguna** [Automattic/pocket-casts-ios#1117]
### Screenshots

| Notice the Right Fade is Red |
|:---:|
|<img src="https://github.com/Automattic/pocket-casts-ios/assets/793774/203a2b8d-265e-427e-98a4-b7b68a3fd46d" width="320" />|

<details>
  <summary><h3>Demo Video</h3></summary>
  
https://github.com/Automattic/pocket-casts-ios/assets/793774/ce835284-cee1-4ff8-87fc-17083108d707

</details>

### Steps to reproduce
1. Add some items to your up next
2. Play an episode
3. Open the full screen player
4. Tap the up next icon
5. Change the current episode to one from a different podcast
6. Dismiss the up next
7. 💥 The fade color will be wrong

**Comment by rviljoen** [comment]
@emilylaguna I think this one can be closed as fixed?

**Comment by emilylaguna** [comment]
Fixed by: https://github.com/Automattic/pocket-casts-ios/pull/1120
