### ISSUE TITLE
Full Size Player Tab Buttons will overlap after minimizing player and language set to German

### ISSUE THREAD

**Issue by johannkirsch** [Automattic/pocket-casts-ios#1122]
### Description

If the app is set to German, the labels in the full size player overlap after you have just displayed the mini player with the same episode. I suppose that has something to do with the relatively long German words.
Playing a new episode fixes this temporarily, however the App will behave the same after minimizing the player.
This bug does not occur on episodes, where no chapters are available and therefore only _Aktuelle Wiedergabe_ (Now playing) and _Beschreibung_ (Notes) are viewed.

### Step-by-step reproduction instructions

1. Set App Language to German in Settings
2. Start playing an episode with chapter marks
3. Minimize Player
4. Maximize Player

### Screenshots or screen recording

![IMG_FE40437102E6-1](https://github.com/Automattic/pocket-casts-ios/assets/44731170/ea23c0c8-bca5-4830-abd0-72c948516000)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

iPhone 8, iOS 16.6.1, Pocket Casts 7.47.0.4

**Comment by leandroalonso** [comment]
@johannkirsch thanks for the report!

Fixed in #1119
