### ISSUE TITLE
Missing episodes in the app for two podcasts published by the same author (France Inter)

### ISSUE THREAD

**Issue by reginabally** [Automattic/pocket-casts-ios#1124]
### Description

We have two similar reports of episodes missing in the app for two podcasts published by the same author (France Inter).

In 6760467-zen, the iOS app displayed 22 episodes to the user, but the Android and web apps showed 31.
RSS feed URL: https://radiofrance-podcast.net/podcast09/35099478-7c72-4f9e-a6de-1b928400e9e5/rss_13940.xml
Internal Slack discussions: p1695268822950099-slack-C02A333D8LQ

In 7013410-zen, the user tapped the notification on the iPhone to download the new episode. However, when the episode was nowhere found in the app when they checked the download status.
RSS feed URL: https://radiofrance-podcast.net/podcast09/35099478-7c72-4f9e-a6de-1b928400e9e5/rss_10212.xml
Internal Slack discussions: p1695274973347129-slack-C02A333D8LQ

### Step-by-step reproduction instructions

Steps to reproduce the second scenario (missing episode when trying to download it):
1. Subscribe to this podcast: https://pca.st/v8OaKd.
2. Enable notifications for this podcast via the Podcast Settings page.
3. Wait for the podcast to release a new episode.
4. When the app sends a notification for a new episode, tap the notification and select "Download".
5. Go to Profile > Downloads to see the download progress.
6. Notice the episode is not listed in the download list.

### Screenshots or screen recording

Video recording for the second scenario:

https://github.com/Automattic/pocket-casts-ios/assets/40906847/90e49be5-3005-4d7b-b114-009dbb4b6a18

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

App Version: 7.47
Device: iPhone14,2
OS: 17.0

**Comment by igotdes** [comment]
The user says the issues persists for them, and I was just able to replicate this issue again with the following steps:

1. Subscribe to the podcast
2. On the web app, there are 41 episodes:

![Markup on 2023-10-31 at 13:43:42](https://github.com/Automattic/pocket-casts-ios/assets/74066241/32a2bc9e-57c9-4c9c-aea4-bffc189cfee3)

3. But on the iOS app, there are only three:

![IMG_E40C5963A2BA-1](https://github.com/Automattic/pocket-casts-ios/assets/74066241/7959b039-a5d4-4def-b327-2297e37660f2)
