### ISSUE TITLE
Overlapping tab titles in german (since iOS 17?)

### ISSUE THREAD

**Issue by Qhilm** [Automattic/pocket-casts-ios#1128]
### Description

The tabs "now playing", "Notes", "Chapters" are overlapping at the top of the app, when a specific podcat episode is open, rendering them unreadable. This does not happen in English, only in German for me (I have not tested other languages).

### Step-by-step reproduction instructions

1. Set app or phone language to german
2. Start playing a podcast
3. Expand the episode over the full screen

### Screenshots or screen recording

![IMG_7953](https://github.com/Automattic/pocket-casts-ios/assets/3350433/6b2ed7ae-0f74-4b19-a05f-434e7d02c3b5)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

iPhone 12 mini, iOS 17.0.1, Pocket Casts 7.47

**Comment by leandroalonso** [comment]
Fixed in #1121
