### ISSUE TITLE
Latest beta: Homescreen Widget not anymore available

### ISSUE THREAD

**Issue by BKrnk1337** [Automattic/pocket-casts-ios#1162]
With the last beta I am not able to use my previously added widgets (they are blank) or add new one.

**Comment by emilylaguna** [comment]
I'm not able to reproduce this on my end. Is this still happening for you?

**Comment by azollafox** [comment]
I think see a user report of this at 7206205-zen on 7.49

**Comment by joashrajin** [comment]
@emilylaguna the user mentioned above says that they removed the widget but do not see it anymore. 

Device info: 

App Version: 7.49
Device: iPhone13,2
OS: 17.0.3

**Comment by emilylaguna** [comment]
@joashrajin hmm. Does this happen even after restarting their device? I tried to reproduce but haven't been able to.

**Comment by joashrajin** [comment]
@emilylaguna I will ask the user :)

**Comment by leandroalonso** [comment]
I'll close this issue. But if it's still happening or if we receive any more reports please feel free to reopen it.
