### ISSUE TITLE
EffectsPlayer always used for downloaded files, even when no effects are enabled

### ISSUE THREAD

**Issue by rviljoen** [Automattic/pocket-casts-ios#1184]
### Description

I have noticed in my device logs that `EffectsPlayer` is always used, even when I have no effects enabled. I have traced this down to the fact that I always download episodes. `DefaultPlayer` is capable of playing downloaded files, speed adjustments and Volume Boost, but `EffectsPlayer` is needed for trim silence. Looking at the logic, when trim silence is enabled, a download is initiated:

https://github.com/Automattic/pocket-casts-ios/blob/da0e130d8b11a77a3002ea69879fcb2ac9d7f069/podcasts/PlaybackManager.swift#L1836-L1841

When building the list of possible players to use, we always add `EffectsPlayer` when a file has been downloaded (in my case by the user and not because trim silence is enabled):

https://github.com/Automattic/pocket-casts-ios/blob/da0e130d8b11a77a3002ea69879fcb2ac9d7f069/podcasts/PlaybackManager.swift#L1086-L1091 

I've been running a test build for the last few weeks which adds a check for trim silence, in addition to the download check:

`(currEpisode.downloaded(pathFinder: DownloadManager.shared) && effects().trimSilence != .off)`

`DefaultPlayer` is then used for all scenarios, except where trim silence is enabled. Toggling trim silence also correctly switches between the correct player.

In my limited testing, `DefaultPlayer` uses about 50% less resources than `EffectsPlayer`, so this could be a big help with battery consumption. I'm not sure what percentage of users use trim silence, but my guess is that many people download episodes, which would then switch them to `EffectsPlayer` even if trim silence is not enabled.

I'm keen to hear from @emilylaguna or @leandroalonso on this issue before submitting a PR.  

### Step-by-step reproduction instructions

As per description above

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

iPhone 14 Pro, iOS 17.1, Pocket Casts 7.50.0

**Comment by leandroalonso** [comment]
> I'm keen to hear from @emilylaguna or @leandroalonso on this issue before submitting a PR.

Heya @rviljoen! I'm keen on testing this!

I think we can add your change and test it throughout the beta period to see if any issues arise because of this change.

**Comment by wahoofan5** [comment]
> > I'm keen to hear from @emilylaguna or @leandroalonso on this issue before submitting a PR.
> 
> Heya @rviljoen! I'm keen on testing this!
> 
> I think we can add your change and test it throughout the beta period to see if any issues arise because of this change.

Hey all! Any update on this being pushed out to the public?

**Comment by rviljoen** [comment]
Hey @wahoofan5 - this change is currently being tested in the latest TestFlight build 7.51. Assuming no issues are found, it could make it into the next public release. I don't know exact timing for that yet, but the team normally release once every 2 to 3 weeks depending on the beta cycle feedback.

**Comment by leandroalonso** [comment]
It should be available next Monday!
