### ISSUE TITLE
Replace MaterialBottomSheet with our own implementation

### ISSUE THREAD

**Issue by pocketcasts** [Automattic/pocket-casts-ios#12]
As of June 2021, Material components for iOS are now in maintenance mode. This means that we need to look at replacing our use of this with our own component (or a different third party one). Here are all the places we use it:

<img src="https://user-images.githubusercontent.com/610217/132159372-7985d845-55f5-4d67-9074-359b7099f005.png" width="400">

### Additional information

turns out iOS 15 has a built in implementation of bottom sheets - `UISheetPresentationController`. I tested it on our effects panel on the player like so:
```
private func showEffectsPanel() {
	let effectsController = EffectsViewController()

	if #available(iOS 15.0, *) {
	    if let sheet = effectsController.sheetPresentationController {
	        sheet.detents = [.medium()]
	        sheet.largestUndimmedDetentIdentifier = .medium
	        sheet.widthFollowsPreferredContentSizeWhenEdgeAttached = true
	    }
	}

	present(effectsController, animated: true, completion: nil)
}
```

And the behavior is virtually identical, maybe even nicer than the material bottom sheet. It also looks the same which is nice:

<img src="https://user-images.githubusercontent.com/610217/143527187-b77d53f3-8d60-49a6-8e7c-a8a65703648b.PNG" width="300">

Once we switch to iOS 15+ we can change to this approach.

**Comment by mylesbarros** [comment]
I'm working on a PR for this

**Comment by rviljoen** [comment]
@mylesbarros May be worth having a look at what Russel did here in his experimental branch: https://github.com/rustyshelf/pocket-casts-ios/commit/713b8eca4ac4caf785b4df7a63477e2979116bf3

**Comment by mylesbarros** [comment]
@rviljoen You have a really good memory 😄 Thanks, I will!
