### ISSUE TITLE
Apple Watch: Can't install on WatchOS 8.8.1

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-ios#1217]
### Description

We've had users on WatchOS 8.8.1 report that they can no longer install Pocket Casts on their Watch. The issue started from 7.47.0.1. The app is listed with an 'Install' icon, but the installation fails without an error message.

Discussion about it: p1696264891612029-slack-C02A333D8LQ

### Step-by-step reproduction instructions

1. Use an older Apple Watch which uses WatchOS 8.8.1
2. Try to install the Pocket Casts app on it

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-ios/assets/16253818/d6fbd126-56fe-4b01-9ad2-bde039ae38d9

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Apple Watch Series 3, WatchOS 8.8.1 and Pocket Casts v7.52.0.2

7304140-zd-a8c

**Comment by joashrajin** [comment]
7252287-zd-a8c

**Comment by joashrajin** [comment]
7202573-zd-a8c

**Comment by joashrajin** [comment]
7112687-zd-a8c

**Comment by joashrajin** [comment]
7113093-zd-a8c

**Comment by leandroalonso** [comment]
For reference: this started after we updated our tooling to Xcode 15.0.

**Comment by lromero16** [comment]
**Update from the original user:**  

It is not working, same as before... but something had changed on the framework or whatever because I had another app with the same problem (Calendars) and now installed correctly. So I guess you are in the right path but not yet.

**Comment by igotdes** [comment]
Reported in #7345665-zen.

**Comment by leandroalonso** [comment]
I contacted the developer of another app that was experiencing the same issue and asked if they would be kind to share what fixed the issue for them. Waiting for a reply. 🤞

**Comment by jochenhebbrecht** [comment]
Hi. I can confirm that the issue is resolved as of version `7.53.0.4`. Thanks for the fix! 👍

**Comment by jochenhebbrecht** [comment]
This problem is happening again, but now with version `7.61`

**Comment by leandroalonso** [comment]
@jochenhebbrecht same watchOS version?

**Comment by jochenhebbrecht** [comment]
Jip, still on 8.8.1. I managed to get it installed again after completely resetting my Apple Watch.
But now I'm unable to login as a 'plus' user, even though I'm properly logged in on my phone

**Comment by leandroalonso** [comment]
@jochenhebbrecht not sure if you're on TestFlight, but if you go back to the previous version, does it work?

**Comment by jochenhebbrecht** [comment]
I used to be on TestFlight with a subscription on Pocket Casts, but that subscription seems to be gone now. Not sure how I can get this back?

**Comment by leandroalonso** [comment]
@jochenhebbrecht if you have any issues with subscriptions please contact support through the app, they will be able to help you there.

**Comment by jochenhebbrecht** [comment]
@leandroalonso contacted support, got my invitation back for TestFlight. I can confirm issue is no longer present in version `7.63 (7.63.0.4)`
