### ISSUE TITLE
App freezing

### ISSUE THREAD

**Issue by jacobweberbowery** [Automattic/pocket-casts-ios#1291]
### Description

The app has been freezing a lot lately, where the screen is still visible but doesn't respond.

### Step-by-step reproduction instructions

I don't have a way to reproduce it. But it seems to happen often when I start a podcast playing, and leave it in the background for a long time while it finishes playing.

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

iOS 17.2, iPhone XR, Pocket Casts 7.5.3

**Comment by leandroalonso** [comment]
Should be fixed by #1292
