### ISSUE TITLE
Automatic playing from downloaded podcasts

### ISSUE THREAD

**Issue by miraelsner** [Automattic/pocket-casts-ios#1300]
### Description

When I finish listening to a podcast episode, another one of the downloaded ones automatically starts after it ends. I don't like that very much. For example, I would like to choose myself which podcast I want to listen to if I don't have one added to the queue. I think it would be good to remove this automatic playback after the end of a certain podcast and then play the next downloaded one and leave it up to the user to choose the next one himself. Could you please take a look at it. Thank you very much.

### Step-by-step reproduction instructions

1. Download some podcasts to your phone.
2. Start listening some podcast episode
3. And when podcast finish, it automatically start some podcast from downloaded, without puting him in a queue.

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

iPhone 12 Pro, iOs 17.1.2, Pocket Cast version: 7.52.1

**Comment by rviljoen** [comment]
@miraelsner Do you have AutoPlay disabled under Settings->General?

![image](https://github.com/Automattic/pocket-casts-ios/assets/25402814/d5e12c09-2dde-41ac-bd73-c8ebe094bad1)

**Comment by miraelsner** [comment]
Yes, I have autoplay on. I change it to off and it solve my problem. Sorry for the wrong report. I didn't know about this setting. Thank you very much for your help.

**Comment by rviljoen** [comment]
You're welcome! Glad I could help.

**Comment by rviljoen** [comment]
@pocketcasts @miraelsner I think we can close this issue 🥳
