### ISSUE TITLE
Nav bar issues on iPhone 13 Mini

### ISSUE THREAD

**Issue by aisajib** [Automattic/pocket-casts-ios#1302]
### Description

A user on [Twitter/X](https://twitter.com/trevorheins/status/1735362832038785248) reported the navbar looking wonky on iPhone 13 Mini. 

### Step-by-step reproduction instructions

I wasn't able to replicate this on my end, but below is a screenshot from the user. 

### Screenshots or screen recording

![GBU_TDaW0AAB-lk](https://github.com/Automattic/pocket-casts-ios/assets/2541844/404d3bb4-ff1f-4cd4-9fdd-eba3f9c10e61)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

iPhone 13 Mini. 
I asked for the app and iOS version.

**Comment by ArrBianca** [comment]
Also on an iPhone 13 mini, I experience the same thing when I start selection mode in a podcast listing.
|<img src="https://github.com/Automattic/pocket-casts-ios/assets/152931252/24709ac6-3f67-492e-9611-3e2791c2b031" width="886">|![](https://github.com/Automattic/pocket-casts-ios/assets/152931252/0c9b5b2c-878e-4405-9126-dacb8891cb6f )|
|---|---|


I notice in the video hitting the red recording oval to show the stop screen recording popup actually bumps the bar back into place.

App version: 7.53.1.0, though I've noticed it before the current update
iOS version: 17.2

**Comment by bjtitus** [comment]
Use in #7633603-zd-a8c reported this issue as well.
