### ISSUE TITLE
Make "Podcast title" tappable in the player and link to podcast screen

### ISSUE THREAD

**Issue by leandroalonso** [Automattic/pocket-casts-ios#1322]
### Discussed in https://github.com/Automattic/pocket-casts-ios/discussions/1313

<div type='discussions-op-text'>

<sup>Originally posted by **david-gonzalez-a8c** December 22, 2023</sup>
Let's make the "Podcast title" in the player tappable and take to the podcast view. This is something that most products in the space have and it makes sense:

<img width="1061" alt="image" src="https://github.com/Automattic/pocket-casts-ios/assets/92024441/78700db1-fc09-456e-b6b1-7a06182f6845">

I don't think we need to make further adjustments in the spacing to make it possible.</div>

**Comment by SergioEstevao** [comment]
Keeping in mind that the player view can be pulled from any tab section I have some questions on how to implement navigation on this:

- Should we push the podcast view inside the player view?
- Or should we navigate to Podcasts or Discover tab and open this specific podcast view?

**Comment by leandroalonso** [comment]
@SergioEstevao I believe the best course of action would be to dismiss the player and then from Podcasts/Discover display the podcast view.

I believe Discover might be a better choice because "Podcasts" contains only the podcasts the user is subscribed to while Discover has everything.

**Comment by SergioEstevao** [comment]
@leandroalonso I did some coding using the current navigation methods and by default opening a podcast using those methods just keeps the current tab open and push navigation to podcast view on top. Is that ok?
