### ISSUE TITLE
Second tap on tab bar doesn't focus on search

### ISSUE THREAD

**Issue by leandroalonso** [Automattic/pocket-casts-ios#1345]
On iOS there's a somewhat common pattern to bring focus on search when tapping the tab bar.

Eg.: if you are already on Discover, another tap on Discover would bring the focus to the search (displaying keyboard, etc).

This used to work but I believe after iOS 17 it stopped.

#7565431-zen

**Comment by bikrrr** [comment]
A second tap on the **Discover** tab now opens the search. Should this issue be closed? 🤔

Or is it left open to revert the change to the **Podcasts** tab behavior? 

A second tap on the **Podcasts** tab now also opens search, which is disorienting. IMO, it should return to the top level of Podcasts as it did before. Here's [my reasoning in the Pocket Casts forum](https://forums.pocketcasts.com/forums/topic/tapping-twice-on-podcasts-tab-causes-search-to-pop-up-very-annoying/#post-2990).

**Comment by leandroalonso** [comment]
> Should this issue be closed? 🤔

Yes! Thanks for the ping. :)

> t should return to the top level of Podcasts as it did before

It should return to the top level and only then it should show the search. Is it not working that way?

**Comment by bikrrr** [comment]
> It should return to the top level and only then it should show the search. Is it not working that way?

No, if the **Podcasts** tab's search field is already visible, a second tap on **Podcasts** will place focus on search and open the keyboard. Then, if you do a search and tap **Podcasts** again (to go back), it'll just open the keyboard again, making it harder to return to the top level.

This behavior changed with the **Discover** tab change. As I mentioned in [that forum thread](https://forums.pocketcasts.com/forums/topic/tapping-twice-on-podcasts-tab-causes-search-to-pop-up-very-annoying/#post-2990), I don't think the **Podcasts** tab should open search as it has a different primary purpose (as does Filters and Profile). **Discover** is the only tab where search is the _primary_ function.

Here's a screen recording starting from **Discover**, where I…
1. Tap **Podcasts**
2. Tap **Podcasts** again
3. Search for "_test_"
4. Tap **Podcasts**

https://github.com/Automattic/pocket-casts-ios/assets/2607653/74e20567-886a-4127-a893-c42b1e93aea2
