### ISSUE TITLE
Episode artwork shows behind the video player

### ISSUE THREAD

**Issue by emilylaguna** [Automattic/pocket-casts-ios#1352]
### Description

When playing a video podcast the episode artwork will appear behind the video. 

### Step-by-step reproduction instructions

1. Launch the app
2. Play a video podcast such as This Week in Tech
3. Open the full screen player
4. 💥 The episode artwork appears behind the player

### Screenshots or screen recording

<img src="https://github.com/Automattic/pocket-casts-ios/assets/793774/d3dc2668-8922-49cb-9f7e-f64b4573af60" width="320" />

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

**Comment by SergioEstevao** [comment]
I'm only seeing this on trunk, production app is working correctly for me.
