### ISSUE TITLE
Folders: Select all action is missing

### ISSUE THREAD

**Issue by adamzelinski** [Automattic/pocket-casts-ios#143]
### Description
Currently, the 'select all' action for folders is not being displayed within the create folder modal.

[**Designs**](https://www.figma.com/file/hxXdVc0icUYyz2fWHT7roh/Pocket-Casts-Folders?node-id=283%3A26776)

<img width="935" alt="Screen Shot 2022-08-05 at 1 09 36 pm" src="https://user-images.githubusercontent.com/74938219/182993361-ca27a982-4b1b-48cf-ba66-5b418cba28d7.png">

**Comment by fsalata** [comment]
Hey man, I gave a try to add this button on #435.
It is not in the figma design but I've changed the button text to "Deselect all" when all podcasts are selected. What do you think?

**Comment by ghost** [comment]
Hey, @fsalata yes thank you "Deselect all" is good with me. I'll make sure it's added to the figma file also
