### ISSUE TITLE
Premium Podcast: Feed Error

### ISSUE THREAD

**Issue by BKrnk1337** [Automattic/pocket-casts-ios#1490]
I financially supported a podcast last year and received a special URL to subscribe to. The subscription has expired and I have now supported the podcast again. My URL has remained the same. If I enter this in the search, I will come to my currently subscribed podcast feed.

However, I am now shown in PocketCast that there is a feed error. However, it is possible to listen to the individual episodes from the feed. Can someone look at the problem?

![image](https://github.com/Automattic/pocket-casts-ios/assets/27677748/d2244745-bcee-43bb-8a61-40d75514ed2d)

**Comment by bjtitus** [comment]
@BKrnk1337 Could you reach out to our support team at support@pocketcasts.com and share the URL so we can refresh it in our backend?

Alternatively, you might try submitting your feed using [this form](https://pocketcasts.com/submit/) and selecting Private. Not sure if that would work but it might be worth a shot.

**Comment by BKrnk1337** [comment]
@bjtitus thank you. I send a mail several days ago with no response till now - crossing my fingers :-)
