### ISSUE TITLE
Check Internet Connection Error

### ISSUE THREAD

**Issue by CameronMilliken** [Automattic/pocket-casts-ios#1504]
### Description

Podcast continues to stop playing seconds after starting it no matter the wifi or cellular connection. 

### Step-by-step reproduction instructions

1. Open [THIS](https://nodeweb.pocketcasts.com/admin/podcasts/4230178?return_url=%2Fadmin%2Fpodcasts%3Fsearch%3Dviper%2Brambles%26limit%3D20%26commit%3DSearch) podcast 
2. Select any episode
3. Playback should stop with the error "Check Internet Connection"

I was able to reproduce this on my end. 

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-ios/assets/36011531/4645f19e-253f-4c13-833f-30c2db49127f

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

App Version: 7.56
Device: iPhone14,3
OS: 17.3

**Comment by rviljoen** [comment]
Unable to reproduce this.

App Version: 7.58
Device: iPhone15,2
OS: 17.4

**Comment by rviljoen** [comment]
@CameronMilliken Are you still able to reproduce this? I'm wondering if it was a temporary issue with the host, if the error was reported against a specific podcast only.

**Comment by CameronMilliken** [comment]
I can no longer reproduce this and will close this for now. Thanks, @rviljoen!
