### ISSUE TITLE
Bug: Multi-Chapter selection  - v 7.60.0.0

### ISSUE THREAD

**Issue by BKrnk1337** [Automattic/pocket-casts-ios#1544]
After today’s update, I noticed that if you swipe back and forth several times in the chapter selection (but can’t describe the specific behaviour exactly), all chapter brands are selected.

Is this a mistake or a feature that is not yet known to me and not described by you.

Here an screenshot of the "view" that I can see:

![image](https://github.com/Automattic/pocket-casts-ios/assets/27677748/31fb0e98-f632-44da-b63c-1a3fd9272a34)

This screen appears when I pressure long on the screen. I remember to read something in the last month about an "de-select" chapter feature. Maybe I just stumbled about it now.

**Second Update:**
I found now the feature request where @rviljoen talked about this feature. But seems it was never released nor described and need definitely some
UI/UX cleanup.

https://github.com/Automattic/pocket-casts-ios/issues/424

**Comment by leandroalonso** [comment]
@BKrnk1337 what are the exact steps to trigger that?

I tried going back and forward many times without success.

**Comment by BKrnk1337** [comment]
@leandroalonso 

I was able to enable it via Long pressing the "chapter view" but disabling is not possible via long press. Disable worked just when I finish the podcast.

**Comment by BKrnk1337** [comment]
I am currently having problems changing the mode back. I am podcast cross-episode selection in the selection and can no longer specifically jump to individual chapter brands. Can you tell me how to deactivate the function again?

**Comment by leandroalonso** [comment]
@BKrnk1337 Sorry, I don't get it. What issue are you experiencing? Can you describe with steps to reproduce it?

There's no way to deactivate the functionatlity.

**Comment by leandroalonso** [comment]
@BKrnk1337 This specific issue has been solved, so I'm gonna close this one. Can you please open a new one with the latest issue you are experiencing? Many thanks!

**Comment by BKrnk1337** [comment]
@leandroalonso Thank you. But the new issue will be the same right? What should i write down there that was not gonna written down here?

**Comment by leandroalonso** [comment]
@BKrnk1337 I didn't get that:

> I am currently having problems changing the mode back. I am podcast cross-episode selection in the selection and can no longer specifically jump to individual chapter brands

What do you mean by changing the mode back? What is cross-episode selection? Could you please elaborate a bit more? Thanks again!

**Comment by BKrnk1337** [comment]
> @BKrnk1337 I didn't get that:
> 
> 
> 
> > I am currently having problems changing the mode back. I am podcast cross-episode selection in the selection and can no longer specifically jump to individual chapter brands
> 
> 
> 
> What do you mean by changing the mode back? What is cross-episode selection? Could you please elaborate a bit more? Thanks again!


I mean switch back to the "non select" mode (the normal one). With the last update there is a new menubar that made it possible. So this case is closed for me _but_

What I think could be better is the colour - the new bar (UI element) is black even when I choose another theme in the appearance menu.

Could you @leandroalonso or @rviljoen dig into this or push a change in the next update. I think the selected theme should influence this UI element as well :)

**Comment by BKrnk1337** [comment]
I don't want to close this issue. Could you open I again? Seems I don't have the rights for this.

**Comment by leandroalonso** [comment]
@BKrnk1337 ops! That's a bug, I'll work on a fix! I tracked it on #1564
