### ISSUE TITLE
Default „Sort Episodes“ changed - not usable

### ISSUE THREAD

**Issue by BKrnk1337** [Automattic/pocket-casts-ios#1555]
### Description

Since the last update of the beta version today to version 7.60.0.2, the global setting in the app for sorting episodes has changed. It is no longer sorted by "Newest to Oldest" but by "Title A-Z".

I also noticed that you can’t select this sorting type at all. If I select one of the four other options, I cannot return to this option.

![image](https://github.com/Automattic/pocket-casts-ios/assets/27677748/35886c35-2d13-4a98-91f7-3fa0ae2236f3)

### Step-by-step reproduction instructions

Open different podcast

### Screenshots or screen recording

![IMG_5452](https://github.com/Automattic/pocket-casts-ios/assets/27677748/27f564ed-e268-4d7c-bd7c-167666f96f02)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

iPhone 15 Pro Max - iOS 17.2

**Comment by lawruhl** [comment]
I have experienced this as well. Was fine before the latest beta.
