### ISSUE TITLE
CarPlay: Star Icon is missing when Extra Playback Actions is enabled

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-ios#158]
### Expected behavior
A star icon should be shown on the Player screen so users can star episodes. This supposed to show once 'Extra Playback Actions' is enabled via the General Settings, since its description mentions: "Adds a mark played and star option to your phone lock
screen and CarPlay."

### Actual behavior

Just a mark played option shows up:
![IMG_1782](https://user-images.githubusercontent.com/16253818/185054540-9651b5d2-9c65-4838-b28e-0aff95e71624.jpg)

### Steps to reproduce the behavior

- Go to Settings > General and enable Extra Playback Actions
- Connect to Apple Carplay
- Play a podcast and notice the player screen

**Comment by rviljoen** [comment]
Could be related to https://github.com/Automattic/pocket-casts-ios/issues/194

**Comment by iAsimov** [comment]
@joashrajin @leandroalonso @rviljoen First of all, I have to say I'm a big fan of your app; it's wonderful. I've come across the issue mentioned by @joashrajin about the missing Star Icon when Extra Playback Actions is enabled on CarPlay. This is particularly important for me and likely for others who frequently use the CarPlay interface.

Understanding that there are several challenges and priorities you're managing, I'd like to kindly ask if it's possible to consider fixing this in the near future. The star feature is a great way to curate episodes, and it's a bit of a gap in the current CarPlay experience.

Thanks for considering this request, and keep up the great work!

**Comment by rviljoen** [comment]
Hi @iAsimov. Unfortunately the fix for this one has to come from Apple. They broke this functionality with the release of iOS 16. It has been reported and escalated, but no feedback as of yet. See issue #194 for more information.

**Comment by rviljoen** [comment]
I had another look at this issue and after further investigation I do not believe that this is the same issue as #194 . Looking at the CarPlay code, we only set up Mark as Played, Rate and Chapter buttons:

https://github.com/Automattic/pocket-casts-ios/blob/ae46fed9d26748f106c04db3cc041851fb2ef503/podcasts/CarPlaySceneDelegate.swift#L121-L150

It should be possible to add a Star button here.
