### ISSUE TITLE
App won't start after update to 7.61.0.2

### ISSUE THREAD

**Issue by BKrnk1337** [Automattic/pocket-casts-ios#1600]
After updating to the current beta version, the app can no longer be started. If I want to start the app, it gets stuck in the initial image (grey black background with the Pocket Casts logo.

**Comment by bjtitus** [comment]
@BKrnk1337 Do you happen to know which version you were upgrading from?

**Comment by BKrnk1337** [comment]
@bjtitus I upgraded from version 7.60.0.5

I skipped the 7.61.0.1

**Comment by leandroalonso** [comment]
@BKrnk1337 if you go back to 7.61.0.1 does it work?

**Comment by BKrnk1337** [comment]
@leandroalonso unfortunately not.
The app is not starting. Going back to the old version

**Comment by leandroalonso** [comment]
@BKrnk1337 let us know if returning to 7.60.0.5 works. If it does, could you please send us your database? Go to Profile > Help & Feedback > "..." (top-right corner) > Export Database

You can mail me the file at leandro.alonso@automattic.com

This will help us debug the issue, I'm not being able to reproduce :(

**Comment by BKrnk1337** [comment]
@leandroalonso i send you the export via mail. I used MailDrop - I hope this way works for you.

**Comment by bjtitus** [comment]
@BKrnk1337 Could you try version 7.61.0.3 from TestFlight? We used your database to test and hope we've fixed the crash. 🙇

**Comment by BKrnk1337** [comment]
> @BKrnk1337 Could you try version 7.61.0.3 from TestFlight? We used your database to test and hope we've fixed the crash. 🙇 

It worked. I can use the app! Thank you.
