### ISSUE TITLE
Volume control for the phone is not working on version 10.4 of WatchOS

### ISSUE THREAD

**Issue by SergioEstevao** [Automattic/pocket-casts-ios#1625]
### Description

Phone playback volume control using the watch crown is not working.

### Step-by-step reproduction instructions

1. Start the app on the Watch 
2. Select the Phone source
3. Start playing a podcast episode
4. Open Now playing
5. Rotate the watch crown
6. See that the volume indicator in the app changes, but the phone volume will not updated.

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Watch OS 10.4

**Comment by rviljoen** [comment]
This may be a WatchOS 10.4 issue, given that multiple apps are experiencing the same:

https://www.reddit.com/r/AppleWatch/comments/1b7rdgv/volume_control_with_crown_not_working_with/

**Comment by igotdes** [comment]
User in #8037846-zen says Pocket Casts is the only app they're having trouble with:

> [...] For further context, Pocket Casts is the only app not responding to the watch commands. Overcast, Spotify and Apple Music and Podcasts are all responding. I love Pocket Casts.

**Comment by igotdes** [comment]
#8021276-zen also says that volume control works fine on other apps:

> Yes, I able to control the volume of other apps which handle media (like Apple Music) or in the default player like that in attached picture.

<details>
<summary>Screenshot from user</summary>

![image0 (3)](https://github.com/Automattic/pocket-casts-ios/assets/74066241/2f1686fa-1740-4a6c-826a-59797f725470)

</details>

**Comment by joashrajin** [comment]
8053035-zd-a8c

**Comment by morpheus1211** [comment]
> User in #8037846-zen says Pocket Casts is the only app they're having trouble with:
> 
> > [...] For further context, Pocket Casts is the only app not responding to the watch commands. Overcast, Spotify and Apple Music and Podcasts are all responding. I love Pocket Casts.

Sorry for the dumb question - where is this quote from? (i.e. can you link to the original issue or forum post or Reddit post or wherever this is taken from? Thanks!)

This is very much NOT my experience. I am using watchOS 10.4 with iOS 17.4.1 and none of the non-Apple audio apps has working volume control when playing audio that is sourced from the phone. I think all of them have working audio if I download the audio to the watch and play it from the watch itself. But for PocketCasts, Overcast, and Spotify definitely if I play something on the phone, controlling the volume from the Apple Watch app just does nothing (the volume dial moves but nothing changes).

EDIT: just to clarify, if I switch to the Now Playing app on the watch, then I can control, but then if I want to say change playback speed or one of the other PocketCasts settings, those are not available in the Now Playing app obviously, so it's quite an annoyance... but again I'm fairly sure this is not a PocketCasts bug so something we'll just be waiting a long time for Apple to get its act together about most likely (again, I could be wrong though).

**Comment by igotdes** [comment]
> where is this quote from? (i.e. can you link to the original issue or forum post or Reddit post or wherever this is taken from? Thanks!)

@morpheus1211 The quote is from a user-submitted message. It's in the Pocket Casts helpdesk system, so the link is internal and can't be shared publicly.

**Comment by fstath** [comment]
> Hello! It seems that you can no longer change the volume using the Digital Crown on Apple Watch. I’ve uninstalled and reinstalled and that didn’t help.

https://www.twitter.com/jlchandler/status/1783268068854059181

**Comment by alevarsir** [comment]
> Last 3 versions of pocket casts for iOS and Apple Watch the volume has not worked. You can spin the crown on the watch and the volume dial changes in the watch face but it has no effect on the volume. All other apps such as Spotify and now playing function fine with adjusting the volume. 

https://www.reddit.com/r/pocketcasts/comments/1cd9y4k/apple_watch_volume_not_working/

**Comment by rviljoen** [comment]
Seems like Spotify found a solution/workaround to the problem:
https://www.reddit.com/r/AppleWatch/comments/1b7rdgv/comment/l0amfbj/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

I tested it myself and Spotify does work now. Overcast still does not, so the fix must have come from Spotify and not iOS. The other thing I noticed is that both Overcast and Pocket Casts have the volume control as an on-screen component (circle at bottom), whereas Spotify and Now Playing have the volume control as overlay on the side. My guess is that these are different components/APIs and that the one PC is using is either broken or deprecated.

![CleanShot 2024-04-26 at 08 53 28](https://github.com/Automattic/pocket-casts-ios/assets/25402814/c10acd28-b084-430f-8d31-e438de7909ff)

**Comment by rviljoen** [comment]
Different controls also pointed out by @bikrrr here: https://github.com/Automattic/pocket-casts-ios/issues/487#issuecomment-1933009793

**Comment by rviljoen** [comment]
Here's an avenue to investigate:
https://forums.developer.apple.com/forums/thread/747224?answerId=785245022#785245022

**Comment by seanogdev** [comment]
This seems to be working again in the latest developer beta

**Comment by morpheus1211** [comment]
A beta of Pocket Casts? Or the developer beta of iOS or watchOS? (If it’s a Pocket Casts beta, is there a place we can sign up? Google did not reveal anything recent.)

**Comment by seanogdev** [comment]
Of iOS , my apologies

**Comment by leandroalonso** [comment]
Just to add a bit of context: this is an Apple issue. It's affecting all apps. Restarting the watch or closing/reopening the app sometimes fixes the issue, but most of the time it doesn't.

**Comment by seanogdev** [comment]
iOS 17.5 should theoretically be out on Monday next week that fixes this

**Comment by rviljoen** [comment]
WatchOS 17.5 fixed this issues.
