### ISSUE TITLE
Dynamic Island suppressed when viewing full player main view

### ISSUE THREAD

**Issue by leandroalonso** [Automattic/pocket-casts-ios#1644]
From a review:

> When the Player window (with Now Plsying, Details, etc) is open, whatever is being displayed in the Dynamic Island is suppressed unless you tap on it or switch between tabs (e.g. from Now Playing to Details) (in which case that display is temporarily enabled. (The Dynamic Island display is also re-enabled if you open the Playback Effects dialog.) (I tried the support email, but it seems that is provided only for premium users.)

To reproduce:

1. Do anything on your phone that will enable something on the Dynamic Island
2. Open Pocket Casts
3. Open the full player
4. Check how the Dynamic Island will be suppressed

**Comment by joashrajin** [comment]
Seems to be related: p1727255706332739/1727255654.167889-slack-C02A333D8LQ

https://github.com/user-attachments/assets/578622b1-401a-4590-9c91-0599dd5c738c

**Comment by SergioEstevao** [comment]
I investigate this and this happens because of this code:

```
override var prefersHomeIndicatorAutoHidden: Bool {
        appDelegate()?.miniPlayer()?.playerOpenState == .open
    }
```

This looks like we did a design decision to hide the Home Indicator on the full screen  player, but it has the side effect of also hide any that is on the Dynamic Island.

@david-gonzalez-a8c or @dcamozzi and thoughts about this?

**Comment by david-gonzalez-a8c** [comment]
I don't see a lot of benefit in hiding the home indicator, in fact the opposite: it removes a basic affordance of the Operating System that is still functional. Moreover, I don't see any other apps doing this. 

I suggest we revert this and show both the Home indicator and the Dynamic Island (being mindful of the needed margins to operate the tabs if the Island is visible)
