### ISSUE TITLE
Refine pills animation in Discover

### ISSUE THREAD

**Issue by david-gonzalez-a8c** [Automattic/pocket-casts-ios#1647]
### Description

The animation when selecting the pills looks a bit clunky, specially when selecting the pills displayed last. Because the pill "travels" a lot of distance, including the scrollable distance to the beginning of the pills container, the animation ends up looking a bit abrupt. With some pills there's also a strange "bounce" effect ("Society and Culture"), can't point out why. Can we please try and smooth it out?

I suggest we either make the pill travel a shorter distance, without the scrollable distance, or adjust the speed of the animation depending on it (longer distance = longer animation). 

I'm attaching a good reference in the app [Cosmos](https://www.cosmos.so/) (let me know if you'd like an invitation).

### Step-by-step reproduction instructions

1. Go to "Discover"
2. Play with selecting and unselecting the pills on top, specially the last ones

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-ios/assets/92024441/facf8527-c694-4352-8cd8-376d3706bc6b

https://github.com/Automattic/pocket-casts-ios/assets/92024441/6de6364d-154d-4304-9d23-0624ff87a322

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

**Comment by bjtitus** [comment]
@david-gonzalez-a8c What do you think of this change to the animation?

https://github.com/Automattic/pocket-casts-ios/assets/3250/321c25ac-ccfc-4dcc-9667-fa0470fc83de

Here it is slowed down:

https://github.com/Automattic/pocket-casts-ios/assets/3250/1f281498-d0f3-4761-a42a-f94e745ecd20

If it looks good, I can submit the code changes!

**Comment by david-gonzalez-a8c** [comment]
Looks great! 

Let's release it, it's a big improvement. I'll check on my devices and suggest further tweaks if needed.
