### ISSUE TITLE
Add default remote keys for all feature flags

### ISSUE THREAD

**Issue by bjtitus** [Automattic/pocket-casts-ios#1716]
### Description

Any feature flag we add currently needs a corresponding `remoteKey` added.

We shouldn't need to do this since any flag should be overridable server side for flexibility.

### Step-by-step reproduction instructions

1. Add a Feature Flag to `FeatureFlag.swift`
2. Add an overwritten value to Firebase Remote Config
3. New value should replace the client-side value

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

**Comment by leandroalonso** [comment]
@bjtitus I think there's one additional test we should do:

1. Add a Feature Flag to FeatureFlag.swift
2. Add an overwritten value to Firebase Remote Config
3. New value should replace the client-side value
4. Delete the Firebase Remote Config one
5. ✅ Local feature flag value should remain the same (we don't want flags to change values when we delete them)

**Comment by bjtitus** [comment]
> ✅ Local feature flag value should remain the same

Are you saying we should store the changed Remote Config value instead of reverting to the value in `FeatureFlag.default`?

Is the idea to cover future flag removal?

I fear this could make it much hard for us to debug issues without knowing which flag values a user should have. As an example, if someone accidentally added a flag and then deleted it, would we be able to determine which value a user should have on their device without needing to fetch logs/data directly from them?

If we do decide to do this, I think it should be done separately from the default values since this would be new functionality on top of just adding a default value for each flag.

**Comment by leandroalonso** [comment]
> Is the idea to cover future flag removal?

Yes!

My main reasoning is: that if an app is working with a flag set to a certain value, it should not change. Think about this scenario:

1. The flag `test` has a default value of `true`
1. We configured this flag to be `false` for versions below `7.60`
2. After some time, we delete flag `test`
3. Now, for versions below `7.60` the flag will change to `true`

> I fear this could make it much hard for us to debug issues without knowing which flag values a user should have. As an example, if someone accidentally added a flag and then deleted it, would we be able to determine which value a user should have on their device without needing to fetch logs/data directly from them?

I agree with you but overall in support requests one of the things we always recommend is to be on the latest version — but I also agree that this is an argument that goes both ways.

> If we do decide to do this, I think it should be done separately from the default values since this would be new functionality on top of just adding a default value for each flag.

In terms of implementation wouldn't that be just a matter of settings flags values only from the list that is returned from the backend? So in case `test` flag is not there anymore, we do nothing with it.

**Comment by bjtitus** [comment]
> In terms of implementation wouldn't that be just a matter of settings flags values only from the list that is returned from the backend?

Yeah, the implementation isn't too bad, I just wanted to make sure it's easily revertible if we end up with issues. I think having a separate commit is fine: https://github.com/Automattic/pocket-casts-ios/pull/1762/commits/0f4659e5d9e8fac2c641517b855e22ddef67bd4e
