### ISSUE TITLE
New grid UI tweaks

### ISSUE THREAD

**Issue by david-gonzalez-a8c** [Automattic/pocket-casts-ios#1799]
### Description

Based on the feedback we've been getting about the new Podcasts grid, I'm suggesting a couple changes that I think will be positive without hurting the spirit of the new UI:

- Decrease the padding between covers from 8dp to 6dp. This will keep the shows apart visually but with bigger tappable areas and possibly reduce the grid illusion effect.
- We've been also getting some complaints about the numeric badges being too small. Let's increase font size from the current H70/11dp to H60/13dp.

[Figma link](https://www.figma.com/design/G60UqxPhTynbalo0Vfr1NC/Playground?node-id=1921-20348&t=SzHu6Z0LDtfXHQKs-1)

### Step-by-step reproduction instructions

...

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

**Comment by leandroalonso** [comment]
Sharing a feedback related to these changes (iPhone 12 mini):

<img width="795" alt="Screenshot 2024-06-11 at 10 59 52" src="https://github.com/Automattic/pocket-casts-ios/assets/7040243/4cdbc02c-0352-4f59-983a-9b97980b2a2f">

**Comment by rviljoen** [comment]
@SergioEstevao Think this one can be closed?

**Comment by SergioEstevao** [comment]
Fixed by: https://github.com/Automattic/pocket-casts-ios/pull/1823
