### ISSUE TITLE
Add support for Double Tap on WatchOS

### ISSUE THREAD

**Issue by leandroalonso** [Automattic/pocket-casts-ios#1828]
### Discussed in https://github.com/Automattic/pocket-casts-ios/discussions/1827

<div type='discussions-op-text'>

<sup>Originally posted by **rviljoen** June 12, 2024</sup>
In iOS 18, apps can now add support for Double Tap. For Pocket Casts, I think the following two app functions are great options for this gesture:
 - Play/Pause
 - Bookmark

Here is the WWDC [video explaining the feature](https://youtu.be/_4t3NCx8LFA?t=633) and here is the [API documentation](https://developer.apple.com/documentation/SwiftUI/View/handGestureShortcut(_:isEnabled:)). </div>

**Comment by rviljoen** [comment]
Implemented via https://github.com/Automattic/pocket-casts-ios/pull/2054
