### ISSUE TITLE
Fix grey shadow in the mini player area (dark themes)

### ISSUE THREAD

**Issue by david-gonzalez-a8c** [Automattic/pocket-casts-ios#1830]
### Description

Not sure if this is the shadow for the tab bar or the gradient behind the mini player, but in the dark themes (Default Dark, Extra Dark, Electricity...) a greyish gradient can be seen in the mini player area:

![IMG_6507](https://github.com/Automattic/pocket-casts-ios/assets/92024441/0a39f5e1-87b0-4d28-9669-2c904f8b10ee)

This should be the same color of the background (primary-ui) with opacity going from 100% to 0%

<img width="716" alt="image" src="https://github.com/Automattic/pocket-casts-ios/assets/92024441/84b11a51-6e52-4536-8119-485c9ff8731d">

### Step-by-step reproduction instructions

...

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

**Comment by leandroalonso** [comment]
cc @SergioEstevao

**Comment by rviljoen** [comment]
@SergioEstevao I think this one can be closed?

**Comment by SergioEstevao** [comment]
Fixed by: https://github.com/Automattic/pocket-casts-ios/pull/1832
