### ISSUE TITLE
CarPlay: Icon Colors are sometimes wrong

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-ios#184]
### Expected behavior

The colors of the icon should be consistent and should not be the same as the background color

### Actual behavior

The icon colors are the same as the background color

<img width="48%" alt="image" src="https://user-images.githubusercontent.com/16253818/186360263-230cda89-3b40-4f4c-90cf-3d696c344461.png"><img width="48%" alt="image" src="https://user-images.githubusercontent.com/16253818/186360309-bc693c1d-5eaf-4846-ad09-b48b566602eb.png">

### Steps to reproduce the behavior

When using the Automatic Background Color setting, the user could replicate this. 
They said:
> It seems intermittent, unfortunately. Sometimes, I will notice during the same podcast it is dark and then later it is light. Sometimes it will start light. I have tried playing around by going in and out of other apps and back to Pocketcasts, but so far have not been able to replicate what causes it. I do think every time it is light and I press it, the next podcast that comes up in the queue is always dark again though. 

More info on the device at #5494705-zen

**Comment by thabotswana** [comment]
Another report in 5582996-zen

>The Mark as played button is not visible because it is shown as white on white. This happens when pocket casts is first opened on Apple CarPlay, the display is on light mode during the day.

App Version: 7.22
Device: iPhone12,8
OS: 16.0
