### ISSUE TITLE
A new auto downloaded episode clears the up next queue

### ISSUE THREAD

**Issue by moniquelive** [Automattic/pocket-casts-ios#1842]
### Description

Whenever a new auto-download episode is added to the up next queue it gets emptied. 

### Step-by-step reproduction instructions

1. Have some episodes on up next queue 
2. Wait for a podcast episode auto download and auto add to up next 
3. Up next queue gets emptied and only the latest download remains in queue

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

iPhone 13 Pro, latest version

**Comment by rviljoen** [comment]
@moniquelive From your description it seems like you are able to consistently reproduce this. Can you please attach a screen recording of when this happens, if possible?

**Comment by moniquelive** [comment]
Actually some update fixed this issue later on. Thanks!
