### ISSUE TITLE
Episode Missing despite New Episode Notification being sent

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-ios#1906]
### Description

We've had a number of recent cases where users mention they get a notification that a new episode is out, but when attempting to click the notification, no episode is found. It gets fixed automatically after a short while (or a few hours)

Internal discussion: p1720592896035089-slack-C02A333D8LQ

### Step-by-step reproduction instructions

@danielebogo was able to replicate so far

### Screenshots or screen recording

N/A

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

**Comment by joashrajin** [comment]
8459719-zd-a8c

**Comment by joashrajin** [comment]
8470226-zd-a8c

**Comment by joashrajin** [comment]
8460134-zd-a8c

> the problem is sporadic. Throughout the day, 25% of the time the app behaves as expected. Other times, a notification comes in and when I click it, it loads the app with a blank screen. And then the opposite occurs where I haven’t received a notification in a couple of hours, I open the app to see if there actually is anything to listen to and the feed loads with multiple podcast episodes that I should have received a notification for. Now, that being said, have you or your colleagues experience any of this?

**Comment by joashrajin** [comment]
8459193-zd-a8c

**Comment by jinnypark** [comment]
> 8470226-zd-a8c

User shared more info:

>  It happened again this morning (logs attached).  It about 1:10pm Eastern I received an iPhone notification for today's episode of the Dan Bongino Show.  When I tapped it, the episode didn't appear in my PocketCasts app to listen to.  
> I just refreshed again now and it still isn't available to listen to even though I can see today's episode available on Apple Podcasts and Spotify now.

Logs: https://mc.a8c.com/includes/img-uploader/files/1721072960-Pocket-Casts-Export.zip

**Comment by igotdes** [comment]
#8490454-zen:

> I get a notification that there’s a new podcast episode but then it doesn’t actually show up in my feed in the app for a delayed period of time - sometimes over an hour

**Comment by igotdes** [comment]
#8491052-zen:
> Is the CDN server working? It's been over 2 hours since any podcasts that I've received notification of have downloaded.

**Comment by igotdes** [comment]
#8491372-zen:

> With the latest builds - I'm routinely getting push notifications for episodes that don't show up in the app until much later. After the push notification, the app will show "no episodes" even if I manually refresh my podcasts. Usually it'll show up an hour or so later.

**Comment by igotdes** [comment]
#8490211-zen:

> Several times recently I’ve seen notifications for new podcast episodes before the episode is actually available. When I tap the notification it doesn’t bring up the episode and the episode doesn’t appear when I refresh the feed manually.

**Comment by igotdes** [comment]
#8491052-zen:

> Is the CDN server working? It's been over 2 hours since any podcasts that I've received notification of have downloaded.
[...]
It's a continuation of the previous issue. During the day (my time zone) there is a variable but significant lag between the time a notification of a podcast being available and it actually becoming available which can reach over 2 hours.

**Comment by joashrajin** [comment]
8490850-zd-a8c

**Comment by emdashcodes** [comment]
8494741-zd-a8c

**Comment by leandroalonso** [comment]
This has been fixed.
