### ISSUE TITLE
Up Next: multi-selection doesn't work

### ISSUE THREAD

**Issue by leandroalonso** [Automattic/pocket-casts-ios#1913]
### Description

When you tap and hold the multi-selection doesn't activate. Tapping "Select All" enabled the "checkboxes" but you can't do anything.

### Step-by-step reproduction instructions

1. Go to Up Next
2. Tap and hold any episode
3. 💥 It will start playing while it should activate the multi-selection
4. Tap "Select All"
5. 💥 You can select episodes but the bar doesn't appear

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

**Comment by rviljoen** [comment]
@leandroalonso I think this one can be closed?

**Comment by leandroalonso** [comment]
Yup! Thanks for the ping.
