### ISSUE TITLE
iOS 16: Extra Playback Actions aren't displayed

### ISSUE THREAD

**Issue by emilylaguna** [Automattic/pocket-casts-ios#194]
### Screenshots
| iOS 15 | iOS 16 |
|:---:|:---:|
|<img src="https://user-images.githubusercontent.com/793774/187513797-af9264e7-03ce-4f71-ad37-9cba44e6c3b7.PNG" height="480" />|<img src="https://user-images.githubusercontent.com/793774/187513683-0cdba6e9-8d65-49b3-8718-32902a6c39e5.png" height="480" />|

### Expected behavior

When the Extra Playback Actions is enabled the Mark Played, and Star actions are displayed on iOS 16.

### Actual behavior
The playback controls are not displayed.

### Steps to reproduce the behavior
1. Launch the app on iOS 16
2. Enable The General > Extra Playback Actions option
3. Play any episode
4. Lock your device
5. Notice the lock screen does not display the extra options.

##### Tested on [device], iOS [version], Pocket Casts [version]
iPhone 8 Plus, iOS 16 Beta 5, 7.21

**Comment by joashrajin** [comment]
+1 5746512-zd-woothemes

**Comment by rviljoen** [comment]
Could be related to https://github.com/Automattic/pocket-casts-ios/issues/158

**Comment by rviljoen** [comment]
Seems like this is an iOS 16.x bug / limitation. I have logged a ticket with Apple Technical Support. Let's see what they come back with.

**Comment by rviljoen** [comment]
Apple Technical Support asked me to log a bug report (FB11862132). They wrote back later with the following:

> Turns out this is a known bug.  If you filed your own bug report, you should be notified of any potential fixes released.  That said what you are doing is supported, you don't need to change your code and it is expected to just start working if/when fixed.

Good to know! Let's hope Apple fixes this soon.

**Comment by emilylaguna** [comment]
@rviljoen Ah! That confirms my suspicion of it being an OS bug. Thanks for checking with Apple. 🤞 it's fixed soon.

**Comment by reginabally** [comment]
Another report in 5799353-zd-woothemes. I will let them know we're waiting for Apple to fix this.

**Comment by mattwondra** [comment]
Another instance: 5826746-zd-woothemes

**Comment by rviljoen** [comment]
Still present in iOS 17 Developer Beta 1. I have sent a follow-up to Apple DTS. Unsurprisingly, no feedback yet via the official Feedback app, despite DTS confirming that it is an iOS bug.

**Comment by leandroalonso** [comment]
Thanks for the update @rviljoen!

**Comment by rviljoen** [comment]
Feedback from Apple Developer Technical Support (DTS):

> Do you see the same issue with this sample?:
> https://developer.apple.com/documentation/mediaplayer/becoming_a_now_playable_app
> If so, file your bug report against that sample.  

I was able to reproduce it with the sample and logged it as FB12398321, as per their instruction. 

@leandroalonso @emilylaguna Do you have a developer rep at Apple that can help us nudge this along?

**Comment by yaelirub** [comment]
I reached out to our Apple rep for help with expediting a fix.

**Comment by emilylaguna** [comment]
Hi @rviljoen our Apple rep got back to us and asked that we capture a [sysdiagnose](https://it-training.apple.com/tutorials/support/sup075) and attach it to the issue. Are you able to add this to the request for us? Thank you!

**Comment by rviljoen** [comment]
@emilylaguna sysdiagnose added to FB12398321, as requested.

**Comment by emilylaguna** [comment]
Thank you @rviljoen!!!

**Comment by rviljoen** [comment]
@emilylaguna  Finally some progress on this item in iOS 17.1! Apple added the ability to favourite music from the lock screen and dynamic island, via a star icon. With _"Extra Playback Actions"_ enabled, this star is now also visible when Pocket Casts plays content.

Lock screen:
![ERR_NETWORK_CHANGED](https://github.com/Automattic/pocket-casts-ios/assets/25402814/319f472f-2077-45e2-bc35-ca733f01db21)

Dynamic Island:
![Marco Arment, Casey Liss](https://github.com/Automattic/pocket-casts-ios/assets/25402814/a15c0eed-f593-47b6-a676-dc99494376fc)

Clicking the star actually works and applies the star in Pocket Casts. It does not update the lock screen UI though (i.e. the star is not filled after clicking it), and you cannot un-star the episode. I'm guessing that we need to notify iOS that the star action was successful, which should then trigger the UI update. I'll look into this to see what we can do.

Still no way to expose the "Mark Played" action, but at least this is trending in the right direction.

**Comment by joashrajin** [comment]
> In the General settings you have Extra Playback Actions - this states that when enabled it will add a Star and Mark Played to the Lock Screen - it only adds the Star whereas I want the Mark Played button as it states it should be there. 

7307402-zd-a8c

**Comment by rviljoen** [comment]
@joashrajin With the release of iOS 16, Apple have removed the ability for us to display the Mark Played button, despite the fact that their documentation states that it should be possible. We have logged this bug with Apple. In iOS 17.1, they re-added the ability for star (and we are busy fixing that functionality in #1194), but unfortunately Mark as Played will not be possible until Apple fixes it in iOS.

**Comment by erricgunawan** [comment]
> When I enable Extra Playback Options, the rewind button is not replaced with a mark played button on the Lock Screen. The star button is added.
>
> I’ve killed and restarted the app multiple times, enabled and disabled this option, but it hasn’t helped.

<details>
  <summary>Screenshot:</summary>
  <br> 
  
![image](https://github.com/user-attachments/assets/48ee4be3-985f-40b2-b6b6-e33e190edb99)
</details>

8565104-zen

We need to test this on iOS 18 and consider to remove if it's still not supported. 

Internal discussion: p1722834310355779-slack-C02A333D8LQ

**Comment by rviljoen** [comment]
I can confirm that the behaviour, as introduced in iOS 16, is still the same in iOS 18. Toggling "Extra Playback Options" does correctly show/hide the star on the lock screen and dynamic island players. I think the easiest for now is just to update the setting description to accurate describe what is currently working: i.e. it adds a star. Remove the reference to mark as played and replacing the skip back button. If Apple re-enables the other options, then we can update the setting text accordingly.

**Comment by leandroalonso** [comment]
> Remove the reference to mark as played and replacing the skip back button. If Apple re-enables the other options, then we can update the setting text accordingly.

Yep! 100% agree.

**Comment by danielebogo** [comment]
With #1995 we changed the copy and will be released in version `7.70`

**Comment by leandroalonso** [comment]
@danielebogo with this change I believe we can close the issue, it wasn't fixed but there isn't much we can do given it was a change in the system.

**Comment by danielebogo** [comment]
Agree. Thanks @leandroalonso for closing it
