### ISSUE TITLE
Search: Specific query trowing "search failed"

### ISSUE THREAD

**Issue by ezebecke** [Automattic/pocket-casts-ios#196]
### Expected behavior

To see all search result for that query

### Actual behavior

Error message: Search Failed "check your internet connection"

### Steps to reproduce the behavior

- Search the query "The best of m". Search fails when the character "m" is added.

##### Tested on iPhone 12 and 6s, iOS 16 and 15.4.1, Pocket Casts 7.20.2

reported in [5514834-zen](https://woothemes.zendesk.com/agent/tickets/5514834)

**Comment by rviljoen** [comment]
@geekygecko I had a quick look at this issue now and could not reproduce it. Is the ElasticSearch migration complete?

**Comment by geekygecko** [comment]
@rviljoen the migration is close and might happen this week. I can't reproduce this issue either. Thanks for checking.
