### ISSUE TITLE
Missing back button - Help & Feedback > "..."

### ISSUE THREAD

**Issue by BKrnk1337** [Automattic/pocket-casts-ios#2035]
If you click on the three dots in the help section, there is no way to cancel this dialogue. You then have to decide on one of the two options shown and only then cancel it. Another button would certainly make sense.

![image](https://github.com/user-attachments/assets/f11af451-bd73-4493-bd3a-d1d035621f0f)

**Comment by danielebogo** [comment]
Thanks @BKrnk1337 for reporting this

**Comment by danielebogo** [comment]
Fix will be out with 7.70
