### ISSUE TITLE
Trim silence breaks playback when switching from iPhone speaker to other audio outputs

### ISSUE THREAD

**Issue by rviljoen** [Automattic/pocket-casts-ios#2049]
### Discussed in https://github.com/Automattic/pocket-casts-ios/discussions/1538

<div type='discussions-op-text'>

<sup>Originally posted by **ajkessel** March 19, 2024</sup>
I've experienced an issue since first installing Pocket Casts at the start of this year: if trim silence is enabled and audio is playing from the iPhone speaker, switching to another audio output (Bluetooth earbuds, speaker, or CarPlay) causes playback to stop. The lock screen shows the player in "play" rather than "pause" mode, but the player is not playing, and tapping play/pause has no effect. The only way to resume playing is to foreground the app and hit play/pause a couple of times.

I've attempted to work through this issue with Pocket Casts support but hit a dead-end.

Wondering if anyone here has ideas for further troubleshooting/narrowing the issue? Apparently it's not widespread, but I can't think of anything that would be unusual about my own setup. I've tried purging and reinstalling the app to no avail. 

FWIW, this is on an iPhone Pro Max 15 now running iOS 17.4. The behavior occurs with various external audio devices: Jabra Elite 75t earbuds, a Sangean H202 speaker, and Hyundai CarPlay.</div>

## Steps to reproduce

1. Play podcast on iPhone speaker
2. Enable Trim Silence
3. Switch to BT headphones (non-Apple)
4. Switch off headphones. Playback should stop
5. Press Play. Playback should start on speaker.
6. Turn on headphones. They will connect to iPhone and playback will stop, instead of continuing on headphones. Player shows pause button, i.e. it thinks it is still playing, but the progress bar is stopped.
7.  You have to press pause and then play again to fix playback.

The above steps were performed in the app, but also happens outside of the app (i.e. when the app is minimized), as initially reported by the user.

**Comment by rviljoen** [comment]
This is quite a complex one and I'm still piecing it all together, but here is what I have learned so far. I believe this bug got introduced with iOS 17 when [AVAudioSession.InterruptionReason.routeDisconnected](https://developer.apple.com/documentation/avfaudio/avaudiosession/interruptionreason/routedisconnected) was added to iOS.

We only see this bug with `EffectsPlayer` because iOS handles the interruption logic in `DefaultPlayer`:
https://github.com/Automattic/pocket-casts-ios/blob/00a5a1dfbde39e9f0813cabcc562987e7475de03/podcasts/DefaultPlayer.swift#L221-L223

In `EffectsPlayer` we handle the route change, i.e. when the playback switches from phone speaker to BT device, here:
https://github.com/Automattic/pocket-casts-ios/blob/00a5a1dfbde39e9f0813cabcc562987e7475de03/podcasts/EffectsPlayer.swift#L335-L346

Couple of things to note here:
 - We take the current state of an interruption into account, whereas iOS handles this in `DefaultPlayer`
 - The conditional logic does not cater for all scenarios. There is no logic for when we should be playing *and* an interruption is currently in progress. In that scenario the code does nothing.

I was able to reproduce the issue with the debugger enabled and confirmed that when this happened `PlaybackManager.shared.interruptionInProgress()` was returning `true` and `shouldKeepPlaying.value` was also `true`, i.e. it triggers the code path which does nothing. So the next question then is why is an interruption in progress? This is the only place where we set the current state of `interruptInProgress`:

https://github.com/Automattic/pocket-casts-ios/blob/00a5a1dfbde39e9f0813cabcc562987e7475de03/podcasts/PlaybackManager.swift#L1804-L1834

The logic seems simple: set to true when interruption starts and set to false when interruption ends. So then I digged deeper and found the following after adding some debug code. When the issue was happening, i.e. `interruptInProgress` was `true` while connecting to external device, the preceding reason for the interruption was `routeDisconnected = 4` which is the newly introduced reason in iOS 17. The description reads: _"The system interrupts the audio session due to a disconnection of an audio route."_

This happens when you are listening via BT headphones and turn them off. We get notified of the interruption and set `interruptInProgress` to `true`. The problem is that we never get notified that the interruption ended, because there is no end event in the case of BT devices being turned off. I think the logic above wrongly assumes that every `AVAudioSession.InterruptionType.began` notification will always be followed by a `AVAudioSession.InterruptionType.ended` notification, which does not seem to hold true.

I'm not convinced just yet that this is the full picture. It's quite possible that there is some other factor or race condition at play as well, but I wanted to document what I found so far for others to review.

**Comment by ajkessel** [comment]
This was working fine for me with the last several builds and now there seems to have been a regression -- i.e. if I'm playing on the speaker and switch to Bluetooth earbuds mid-stream, it now stops. The problem is a little different from before. Before, the lock-screen icon would show playing but it would not actually play. Then it was fixed for several releases. Now when I put in earbuds, it switches to stop. And if I hit "play" if often doesn't work and needs to be tapped multiple times.

debug log shows
```
2024-10-22 13:44:58 PlaybackManager Play The Art of Being Single userInitiated: true
2024-10-22 13:44:58 activating audio session succeeded
2024-10-22 13:44:58 More than 1 hour since this episode was paused, jumping back 15 seconds
2024-10-22 13:45:08 saving played up to 1229.9012244897958 for episode The Art of Being Single
2024-10-22 13:45:08 Sent position 1229 status 2 for episode The Art of Being Single to server
2024-10-22 13:45:39 Remote control: playCommand, treating as playPause
2024-10-22 13:45:39 PlaybackManager pausing playback The Art of Being Single
2024-10-22 13:45:39 saving played up to 1231.1551020408162 for episode The Art of Being Single
2024-10-22 13:45:39 cleanupCurrentPlayer permanent? true
2024-10-22 13:45:42 deactiveAudioSession succeeded
2024-10-22 13:45:45 deactiveAudioSession succeeded
2024-10-22 13:45:56 Show Info: returning cached data for episode d3a490cd-09a1-4e95-8f54-942b561b77f5
```
