### ISSUE TITLE
Clip sharing: Really laggy - Beta 7.72.0.1

### ISSUE THREAD

**Issue by BKrnk1337** [Automattic/pocket-casts-ios#2124]
I want to try out the new clip sharing function. The podcast episode has a runtime of nearly three hours. 

When I try to scroll inside the timeline after selecting the "clip sharing" the horizontal waveform is really laggy.

Furthermore it is not possible to stop the audio with play / pause button from the clip sharing.

**Comment by bjtitus** [comment]
@BKrnk1337 Would you be willing to share the episode you tried?

**Comment by BKrnk1337** [comment]
> @BKrnk1337 Would you be willing to share the episode you tried?

Yes - sorry that I did not add it already.

https://pca.st/episode/774bbde4-05ea-449f-92a3-0db9a5d1740e

Furthermore i think it would be good to change the part of the audio i want to "clip share" more easily. At the moment I can't (easily) select another part to share. For example I want to share but then go back or forth 20 minutes.

**Comment by bjtitus** [comment]
> At the moment I can't (easily) select another part to share. For example I want to share but then go back or forth 20 minutes.

We're working on adding zoom and also some gestures to quickly move the handles. Is there anything else you think would make that easier?

**Comment by BKrnk1337** [comment]
> > At the moment I can't (easily) select another part to share. For example I want to share but then go back or forth 20 minutes.
> 
> 
> 
> We're working on adding zoom and also some gestures to quickly move the handles. Is there anything else you think would make that easier?

Sounds great. Maybe a time indicator?

**Comment by bjtitus** [comment]
This lag is mostly fixed in the current versions. Let us know if you experience any other lag with clip creation.
