### ISSUE TITLE
Add a setting to disable scrubbing on the lock screen

### ISSUE THREAD

**Issue by bjtitus** [Automattic/pocket-casts-ios#2200]
### Description

This is a feature found in several audio apps. See the thread in pdjfGa-Kp-p2 for user feedback on this.

We should be able to ignore the `MPRemoteCommandCenter.changePlaybackPositionCommand` or other callbacks.

### Did you search for existing list?

- [X] I have searched for existing issues.

**Comment by rviljoen** [comment]
@bjtitus This is a great quality of life improvement. The solution to this is to not add a target `MPRemoteCommandCenter.changePlaybackPositionCommand`, i.e. if the setting is enabled then skip this code:

https://github.com/Automattic/pocket-casts-ios/blob/bf66a503acc62854b87932020ea9dbd74dd62073/podcasts/PlaybackManager.swift#L1647-L1666

If been running this change in my dev builds for a few months and it works great. It disables the scrubber on the lock screen and Dynamic Island controls, but keeps the skip buttons active.

**Comment by silellak** [comment]
Just wanted to add that I’d love to see this feature added! Would be a huge quality of life improvement.

**Comment by iamfromreallife** [comment]
It's so infuriating the amount of times I lost my position on podcasts because of accidentally scrubbing on the lock screen. Please add that option, please.

**Comment by dr3141** [comment]
Couldn't agree more, please add this as an option.

**Comment by joashrajin** [comment]
9081317-zd-a8c
