### ISSUE TITLE
Tint mode in iOS 18 breaks colors in Widgets

### ISSUE THREAD

**Issue by danielebogo** [Automattic/pocket-casts-ios#2212]
### Description

Few reports:

_Update to the bug I just reported regarding tint mode on iOS 18. I reinstalled the store version, and the widget does not tint, but nor does it become all white. It just retains its usual look. I then reinstalled the beta and the problem returned. So perhaps if you’re working on implementing the feature in the beta something is awry with it. Thanks!!_

_Bug report: When I use the new customize Home Screen function tint mode, the Pocket Casts widgets are blank white with maybe a hint…hint!…of tint. The play button still works, but it’s invisible. When I leave tint mode, they go back to normal. This may only be in the most recent Beta. I am not sure, but I think it was working normally on the App Store version before I reinstalled the beta. They also show up pure white in the widget picker, and this persisted after a device restart._ 

### Step-by-step reproduction instructions

1. Use a device with iOS 18 installed
2. Change the home screen appearance to tint color
3. Look at the Widget colors

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

iOS 18

**Comment by jacksonzamorano** [comment]
I am also experiencing this issue.

**Comment by joashrajin** [comment]
8816547-zd-a8c

**Comment by Pjhugo3927** [comment]
Same here…

**Comment by mdrockwell** [comment]
Another case in 8839889-zd-a8c

**Comment by danielebogo** [comment]
Fix deployed in 7.74 beta 3
