### ISSUE TITLE
Consolidate search bars

### ISSUE THREAD

**Issue by david-gonzalez-a8c** [Automattic/pocket-casts-ios#2259]
### Description

The search bar in "Bookmarks" looks oddly different from the other ones in the app like the one in "Podcasts", "Discover" or "Listening history". Can we please consolidate these?

![Image](https://github.com/user-attachments/assets/f006165a-6643-4ef9-b10c-4a67712199fa)
![Image](https://github.com/user-attachments/assets/483f56ce-46d1-4c60-a467-a1e55a3b0f4b)

### Step-by-step reproduction instructions

1. Go to "Profile" and "Bookmarks"
2. Compare the search bar to the ones found in "Podcasts", "Discover" or "Listening history"

### Did you search for existing bug reports?

- [x] I have searched for existing bug reports.

**Comment by rviljoen** [comment]
I think the differences are due to two different UI technologies being used (UIKit and SwiftUI). Not sure if they can be exactly the same.

**Comment by SergioEstevao** [comment]
@david-gonzalez-a8c what is the style that you prefer ?

**Comment by SergioEstevao** [comment]
Here is Bookmarks with styling to match the one in other views:

![Image](https://github.com/user-attachments/assets/d42be194-c594-4af6-8090-9974485a5858)

Looking at the code I needed to do the following changes:

- Update the icons being used
- Update colors
- Update font

The Bookmarks search component being used is more recent and done in SwiftUI, so I'm not sure if we want to change it to reflect the older component or the other way around.

**Comment by david-gonzalez-a8c** [comment]
The style we have in "Podcasts" or "Discover" looks more native to me, more similar to what Apple Music or Podcasts has (which is a good thing in my eyes, because of familiarity), so I'd prefer if we apply that style everywhere.

**Comment by SergioEstevao** [comment]
@david-gonzalez-a8c when applying the same colors I detected an issue with the classic theme:

![Image](https://github.com/user-attachments/assets/957d26fb-1eff-45e1-80e4-0d2399a84c07)

On the other search bars (Discovery and Podcast) the search bar colors work because we are using a different background color for search that matches the Navigation bar color

![Image](https://github.com/user-attachments/assets/c3382a4a-e485-44b3-83c4-5039f1677719)
