### ISSUE TITLE
Vacuum db for new version

### ISSUE THREAD

**Issue by danielebogo** [Automattic/pocket-casts-ios#2289]
We would like to test the db vacuum when a new release is out. Let's use a FF to control it.

**Comment by bjtitus** [comment]
If we're going to vacuum on each app release would it make sense to consider vacuuming more regularly, like every launch or every X number of days?

**Comment by danielebogo** [comment]
@bjtitus  🤔 not sure. Considering our release cadence, we will vacuum at least every 2 weeks. Perhaps every week?
