### ISSUE TITLE
Radioactivity theme causes the app to freeze/unresponsive when the iOS share menu appear

### ISSUE THREAD

**Issue by dericleeyy** [Automattic/pocket-casts-ios#2411]
### Description

When the "Radioactivity" theme is used in Pocket Casts, sharing a podcast or episodeb and using the "More" option causes the app to freeze when the iOS share menu pops up.

### Step-by-step reproduction instructions

1. Go to Profile > Settings > Appearance
2. Select the Radioactivity theme in the current Light/Dark mode
3. Go to a podcast episode
4. Share > More

### Screenshots or screen recording

![Image](https://github.com/user-attachments/assets/56baa3ed-b13b-4616-b27c-cc8834360db6)

### Did you search for existing bug reports?

- [x] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

iPhone 16 Pro Max
iOS 18.1
Pocket Casts 7.76

**Comment by dericleeyy** [comment]
Reported by 8934306-zen

**Comment by danielebogo** [comment]
@bjtitus would you mind to have a look?
