### ISSUE TITLE
AirPlay Issues after v7.76.1

### ISSUE THREAD

**Issue by igotdes** [Automattic/pocket-casts-ios#2429]
### Description

User in #9039831-zen reports an issue with AirPlay to their Sonos speakers turning on and off intermittently:

> After your last update, Airplay is not working properly on iOS. It keeps turning on and off repeatedly. I’m using my iPhone and a Sonos speaker, playing the podcast via Airplay from my iPhone to the Sonos speaker. After starting, Airplay goes on, off, on, off, on, off—it’s not a smooth transmission anymore. I tested with other podcast apps, and they work without any issues. Thank you for your help.

### Step-by-step reproduction instructions

We haven't been able to replicate the issue so far.

### Did you search for existing bug reports?

- [x] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

App Version: 7.76.1
Device: iPhone16,1
OS: 18.1

**Comment by igotdes** [comment]
The user added:

> It only happens with AirPlay on my Sonos speakers! Unfortunately, I can only test this because I don’t have any other devices with AirPlay. With other apps, AirPlay works without any issues. When using your connection through the Sonos 2 app, it also works without any problems. This issue occurs with all of my different Sonos devices. I am using the Sonos 2 controller.

**Comment by dericleeyy** [comment]
I could reproduce this issue airplaying to my LG tv and also Apple TV.

**Comment by dericleeyy** [comment]
https://github.com/user-attachments/assets/fb94bb3d-2df5-439b-b7db-1b38065f4321

**Comment by dericleeyy** [comment]
Reported in 9065822-zen  and 9065309-zen

**Comment by dericleeyy** [comment]
Reported by https://forums.pocketcasts.com/forums/topic/pausing-when-using-airplay/

**Comment by dericleeyy** [comment]
9042883-zen

**Comment by dericleeyy** [comment]
9062350-zen

**Comment by dericleeyy** [comment]
A temporary fix has been applied to the server side, and AirPlay should work properly now.
A permanent fix would be released as part of #2464.

**Comment by SergioEstevao** [comment]
Solved by 7.77
