### ISSUE TITLE
Car play shows black squares instead of podcasts artwork

### ISSUE THREAD

**Issue by yaelirub** [Automattic/pocket-casts-ios#27]
![IMG_1521](https://user-images.githubusercontent.com/1335657/178425272-48cec479-c098-4d65-a04b-ae5bf947ae25.jpg)

Car hyundai Ioniq 2020, Hybrid
Device: iPhone 11 pro, iOS 15.0

**Comment by emilylaguna** [comment]
Closing as, this should be fixed by: 
- https://github.com/Automattic/pocket-casts-ios/pull/88

If not that then this: 
- https://github.com/Automattic/pocket-casts-ios/pull/705
