### ISSUE TITLE
iOS 14: episode count text does not render

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-ios#287]
### Expected behavior

The text showing the number of episodes and the amount archived should be readable on iOS 14 devices since we support iOS 14.1+

### Actual behavior

The text cannot be read when using iOS 14. Tested the Default Light, Default Dark and Dark Contrast themes: 

<img width="33%" alt="image" src="https://user-images.githubusercontent.com/16253818/192557900-b42aa8f8-770a-470b-9113-5510d27c08ac.png"><img width="33%" alt="image" src="https://user-images.githubusercontent.com/16253818/192557991-fb865fa3-96dd-4ef6-8948-5492fc2cb682.png"><img width="33%" alt="image" src="https://user-images.githubusercontent.com/16253818/192558074-bc6d5c2e-94d7-441b-a713-65bec624f89a.png">

In comparison, here is iOS 16: 

<img width="33%" alt="image" src="https://user-images.githubusercontent.com/16253818/192559333-fdfa77ed-f454-48a0-8060-4644be4e00b2.png"><img width="33%" alt="image" src="https://user-images.githubusercontent.com/16253818/192559561-b9e00e19-8ac7-469a-aa23-0da433ca5e22.png"><img width="33%" alt="image" src="https://user-images.githubusercontent.com/16253818/192558725-2cfb89da-2de7-49ca-91ae-20dcd8bffb8a.png">

### Steps to reproduce the behaviour

- Use a device which uses iOS 14 (Browserstack will do too)
- Open Pocket Casts, then view a podcast page
- You should then see the text hidden

**Comment by jgcaruso** [comment]
Found a simpler change that didn't involve any code and works in iOS 14, 15 and 16
