### ISSUE TITLE
iPhone 14 UI Issues

### ISSUE THREAD

**Issue by igotdes** [Automattic/pocket-casts-ios#327]
### Expected behavior

On a podcast's page, there should be no gap between the podcast title and the search bar. Here's an example of how it appears on an iPhone 11:

<details>
<summary>Screenshot</summary>

![IMG_D3B67627A87E-1](https://user-images.githubusercontent.com/74066241/193167992-17a75c2f-623f-42bf-8aff-f92ebddfb4eb.jpeg)

</details>

There is also no issue on an iPhone SE 2022 and iPhone 13.

### Actual behavior

On an iPhone 14 Pro, there is a gap between the podcast title and the search bar, which results in the episode list being visible through the gap:

<details>
<summary>Screenshot</summary>

![Attachment (1)](https://user-images.githubusercontent.com/74066241/193168174-a3970b2d-4301-4169-94bd-e307f0acfcb2.png)

</details>

### Steps to reproduce the behavior

1. On an iPhone 14 Pro, open a podcast page
2. Notice that there is a gap between the podcast title and the search bar

- We've been able to replicate this.
- Reported on #5581011-zen: iOS 16.0.2, Pocket Casts 7.22

---

### Expected behavior

When either (1) swiping left to archive an episode, or (2) toggling Show/Hide Archived, there should be no white bar at the top of the podcast page. This is how it is on an iPhone SE 2022, for example.

### Actual behavior

On an iPhone 14 Pro, when either (1) swiping left to archive an episode, or (2) toggling Show/Hide Archived, a white bar appears briefly at the top of the podcast page.

<details>
<summary>Screen Recordings</summary>

https://user-images.githubusercontent.com/74066241/193181068-fed34d74-86ff-493b-8894-012fa7d2e235.mov

https://user-images.githubusercontent.com/74066241/193181105-c7611ceb-6020-4749-82de-8d969c798f89.MP4

</details>

### Steps to reproduce the behavior

1. On an iPhone 14 Pro, open a podcast page
2. Swipe left to archive an episode or toggle Show/Hide Archived
3. Notice how a white bar briefly appears at the top of the podcast page

- We've been able to replicate this.
- Reported on #5589565-zen: iOS 16.0.2, Pocket Casts 7.22

**Comment by joashrajin** [comment]
I’ve found issue 1 is resolved on iOS 16.1


https://user-images.githubusercontent.com/16253818/197608141-3b5f532c-8e7c-4be9-959f-defae3b88b07.MOV

**Comment by rviljoen** [comment]
@igotdes I think this has been fixed by https://github.com/Automattic/pocket-casts-ios/pull/328
