### ISSUE TITLE
Crash: DataManager crash on init

### ISSUE THREAD

**Issue by pocketcasts** [Automattic/pocket-casts-ios#34]
Our top Firebase crash at the moment is a `DataManager` crash on init.

```
DataModel
DataManager.swift - Line 15860
DataManager.init() + 15860
```

At first this just looks like something went wrong with statically allocating a DataManager. On closer inspection though, this crash is always from the `ShortcutManager` class, which is a little suspicious.

The first thing I notice is that for some reason we init this class like this in AppDelegate:
```
private lazy var shortcutManager: ShortcutManager = .init()
```

The other possible odd thing is that all of these updates run from the global dispatch queue:
```
DispatchQueue.global().async {
```

Which for this crash is always the queue that crashes:
```
Crashed: com.apple.root.default-qos
EXC_BREAKPOINT 0x0000000102195224
```

**Comment by SergioEstevao** [comment]
No longer happening.
