### ISSUE TITLE
Add Haptic feedback to the pull to refresh

### ISSUE THREAD

**Issue by emilylaguna** [Automattic/pocket-casts-ios#350]
### Expected behavior
When the user swipes down trigger haptic feedback when the user can release to refresh.

### Actual behavior
Nothing happens right now.

### Steps to reproduce the behavior
N/A

##### Tested on [device], iOS [version], Pocket Casts [version]
N/A

**Comment by mylesbarros** [comment]
This is implemented and unless I'm mistaken can be marked as closed

**Comment by emilylaguna** [comment]
Closed as it was implemented in: https://github.com/Automattic/pocket-casts-ios/pull/351
