### ISSUE TITLE
Crash: app crashes when there is no data connection

### ISSUE THREAD

**Issue by pocketcasts** [Automattic/pocket-casts-ios#36]
I noticed that my app crashed (7.20 Beta) when I lost internet reception temporarily. To replicate it, you can:

- Open Pocket Casts
- Choose a Podcast and have the episodes list open
- Switch your WiFi and Mobile Data off
- Try to play an episode (try a couple). The app should then freeze, then crash after a few mins of being frozen

Screen Recording: 

https://user-images.githubusercontent.com/16253818/169473118-1dcac310-90e6-4292-9613-e8a651e51cbd.MP4

**Comment by rviljoen** [comment]
Unable to reproduce this using the steps above on v7.51. App correctly shows an error message on the failed episodes, but does not crash.

**Comment by SergioEstevao** [comment]
Testing this on the current version 7.77 and it's not happening anymore.
