### ISSUE TITLE
France translations not being reflect for fr-CA

### ISSUE THREAD

**Issue by leandroalonso** [Automattic/pocket-casts-ios#390]
Our project on GlotPress says:

> The translations to French (Canada) will automatically fall back to French (France) (default)

However, it seems that the new translations aren't being generated for fr-CA. Take for example the key "watch", in `fr` it's correct: "Montre". In `fr-CA` it's wrong: "Regarder".

**Comment by leandroalonso** [comment]
@mokagio can you help me with that?

**Comment by mokagio** [comment]
My understanding of the fallback mechanism is that `fr-ca` will use the translation for a key from `fr` when there isn't one for `fr-ca`.

E.g. 

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/1218433/196096468-0aec95a6-77f7-46b6-8342-5b57dc24d202.png">

In the case of `watch` and many other keys in `fr-ca` there already is a dedicated translation, so `fr` is not used.

I think GlotPress shows custom vs fallback translations by making the latter semi-transparent:

<img width="1782" alt="image" src="https://user-images.githubusercontent.com/1218433/196096865-1d12dc18-5221-4f7d-805a-99a5bddf3683.png">

**Comment by leandroalonso** [comment]
Oh, I didn't know that.

I updated the `watch` keyword for `fr-CA` and it looks like the tool already picked up: https://github.com/Automattic/pocket-casts-ios/blob/919766e83dce5ee6782ba53fe15988c993045a54/podcasts/fr-CA.lproj/Localizable.strings#L2117
