### ISSUE TITLE
CarPlay: Up Next is Missing

### ISSUE THREAD

**Issue by DustinHartzler** [Automattic/pocket-casts-ios#427]
### Expected behavior

When you launch PocketCasts with CarPlay, you should be prompted to see the Up Next play list at the top of the Podcasts page. This should be the section that shows the 4 next podcasts.

### Actual behavior

I only see this ~50% of the time. Sometimes it works fine and other times I just see the folders of podcasts and no way of navigating to the Up Next playlist

### Steps to reproduce the behavior

I con't replicate. I'll report back if/when I reliably can.

##### Tested on [device], iOS [version], Pocket Casts [version]

CarPay, with iOS 16 with Pocket Casts 7.21.0.1 (TestFlight version)

**Comment by DustinHartzler** [comment]
With some more testing, it seems if you let your podcast keep playing when you turn off the car, when your phone connects to CarPlay the next time, it will auto-start playing, but the Up Next playlist is not displayed.

**Comment by reginabally** [comment]
Another report in 5809380-zd-woothemes.

> CarPlay for as long as I can remember the up next boxout in app is a bit intermittent sometimes it’s there to use and other times only if it’s playing already.

App Version: 7.29
Device: iPhone13,3
OS: 16.2

**Comment by emilylaguna** [comment]
I was able to reproduce this using the following steps in the iOS Simulator:

1. Launch the app
2. Play an item
3. Pause the item
4. In the simulator, Go to I/O > External Displays > CarPlay
5. Once it launches you'll see your up next queue
6. Click the X to close the CarPlay simulator
7. Play the episode
8. Open CarPlay Simulator again
9. 💥 The Up Next will not be displayed

| Episode Not Playing when Connected | Episode Playing When Connected |
|:---:|:---:|
|<img width="300" alt="Screen Shot 2023-01-27 at 4 49 40 PM" src="https://user-images.githubusercontent.com/793774/215207928-5369dcc7-dae8-4cd2-b599-d3e4bb73a149.png">|<img width="300" alt="Screen Shot 2023-01-27 at 4 49 52 PM" src="https://user-images.githubusercontent.com/793774/215207919-5145ec27-e649-4f71-9151-64e254329d53.png">|
