### ISSUE TITLE
Import OPML from a URL

### ISSUE THREAD

**Issue by geekygecko** [Automattic/pocket-casts-ios#442]
### What problem does this address?

It would be great to add the ability for a user to enter a URL of an OPML and for Pocket Casts to import the podcast subscriptions.

Below is the user's suggestion. 
> it would be nice if they took a URL for importing an OPML file. 
https://twitter.com/davewiner/status/1583551708621217792

### What is your proposed solution?

The "Import/Export OPML" settings section could have another option to add by URL.

<img  width="300" src="https://user-images.githubusercontent.com/308331/197679408-9081600e-3180-4e5c-8753-6ace705b0583.jpeg" /> <img  width="300" src="https://user-images.githubusercontent.com/308331/197679420-803da309-31b2-4369-853c-690172e4b7f2.jpeg" />

The option could be something like "By URL" with the description "Import your podcasts from an OPML file using a URL."

It might be best to follow a similar approach to the import from file code. The import by URL could download the content to the device and use the existing logic to parse the OPML file and subscribe to the podcasts.

Here is a URL that can be used for testing https://lists.pocketcasts.com/cdba0d8f-28ed-4654-bcb9-c65990f7399f.opml

This is the Android version of [the issue](https://github.com/Automattic/pocket-casts-android/issues/480) and [pull request](https://github.com/Automattic/pocket-casts-android/pull/482) of the change.

**Comment by yaelirub** [comment]
The screen looks different  and more modern on Android. Lets update the screen on iOS for parity 
<img  width="300" src="https://user-images.githubusercontent.com/1335657/199153053-b7e4ff47-bf28-4da5-8ba2-1c6de74cf503.png" />
