### ISSUE TITLE
Feature request: allow private RSS feed

### ISSUE THREAD

**Issue by laurentftech** [Automattic/pocket-casts-ios#449]
Hi. 
I am using podsync (https://github.com/mxpv/podsync ) to create my own personal podcasts rss feeds on my internal network. Could you please consider allowing private RSS subscription in Pocket Casts?
Thank you.

**Comment by rossbates** [comment]
It's not obvious but if you paste the private URL into the search bar in Discover it will allow you to subscribe to the feed. It's useful for private links like Patreon subscriptions or personal feeds of content from YouTube. 

If you're hosting it on an internal network your going to need to have some sort of proxy or port forwarding for the indexing service to discover it. As far as I know all subscriptions are maintained on a centralized podcast repository.

**Comment by laurentftech** [comment]
> If you're hosting it on an internal network your going to need to have some sort of proxy or port forwarding for the indexing service to discover it. As far as I know all subscriptions are maintained on a centralized podcast repository.

Yeah. That's my problem. I already tried that but I cannot open my internal network with port forwarding because my ISP only propose CGNAT IP.

**Comment by rossbates** [comment]
Huh, yeah the idea of having the iOS client poll multiple endpoints, while not a trivial update, is not the biggest blocker here. The bigger issue is probably account sync and the web player as the concept of a local feed impacts how the paid services would need to function. 

We're getting way off topic now but one option would be to setup a tailscale node outside your internal network that could do the routing from a public interface.

Another option I've used you might want to look into is pushing your feed to an AWS S3 bucket or Azure Storage account. Both of those have free tiers that can serve http content and it's very low hassle.
