### ISSUE TITLE
Feature Request: Folders as Filter Criteria

### ISSUE THREAD

**Issue by rossbates** [Automattic/pocket-casts-ios#451]
With the recent release of folders in Pocket Casts it would be amazing if a folder could be used as criteria for a filter. Folders are a great proxy for categories or topics, and while you can currently select individual episodes you have to remember to maintain the filters when you add/remove subscriptions. Sometimes I'll subscribe to shows for a specific guest or two and decide later if I want to keep it around.

If a filter for example could be the combination of Folder + Downloaded || Starred it would be a powerful way to maintain dynamic playlists based on podcast content type (Entertainment, Philosophy, News, etc...) 

![54343](https://user-images.githubusercontent.com/103388/198181693-e8f823e4-f133-48f7-86e5-9c09fa1cd792.jpg)

**Comment by CookieyedCodes** [comment]
Agreed I would love this too especially if the sort order can go off of the folder order :)

**Comment by leandroalonso** [comment]
Heya @rossbates! Thanks for your request, I'm closing this Issue because feature requests/ideas should go to our  [Discussions](https://github.com/Automattic/pocket-casts-ios/discussions) section! Please feel free to open a topic there, thank you!
