### ISSUE TITLE
How can translate the app?

### ISSUE THREAD

**Issue by comunicamenorca** [Automattic/pocket-casts-ios#459]
Hello,

where are the files to translate Pocketcasts?

**Comment by leandroalonso** [comment]
Hey @comunicamenorca,

You can search for `Localizable.strings` files. However, the translation is done automatically by our tooling, and they come from https://translate.wordpress.com/projects/pocket-casts/ios/

**Comment by comunicamenorca** [comment]
I would like to collaborate with the translation in another language
(Catalan). How can I do it? Can you add this language in the tool in
WordPress?

**Comment by comunicamenorca** [comment]
I would like to collaborate with the translation in another language (Catalan). How can I do it? Can you add this language in the tool in WordPress?

**Comment by leandroalonso** [comment]
I'll talk to the team and get back to you. :)

**Comment by comunicamenorca** [comment]
Hello, Leandro. Any news? Thanks!

**Comment by leandroalonso** [comment]
@comunicamenorca Catalan is now ready to accept translations: https://translate.wordpress.com/projects/pocket-casts/ios/ca/default/

**Comment by comunicamenorca** [comment]
Great, thanks!

Missatge de Leandro Alonso ***@***.***> del dia dl., 5 de
des. 2022 a les 19:12:
