### ISSUE TITLE
Feature request: Synchronization with gpodder/Nextcloud

### ISSUE THREAD

**Issue by MarkWieczorek** [Automattic/pocket-casts-ios#464]
## Feature request: Synchronization with gpodder/Nextcloud

Many people probably use several different podcasts apps on different platforms. Synchronizing the shows that you are subscribed to, and the state of the episodes you are listening to can be complicated and time consuming. A standard way to do this is by using gpodder.net, as well as the gpodder plugin for Nextcloud. In the present state, however, PocketCasts does not support syncrhonization with gpodder. Now that PocketCasts is opensource, this would be a great feature to have!

**Comment by AKDub** [comment]
This would allow syncing with Antennapod in android which would be great.

**Comment by leandroalonso** [comment]
Hi @MarkWieczorek! Thanks for your request, I'm closing this Issue because feature requests/ideas should go to our  [Discussions](https://github.com/Automattic/pocket-casts-ios/discussions) section! Please feel free to open a topic there, thank you!
