### ISSUE TITLE
AirPlay/HomePod: Up Next Queue Doesn't Continue Playing

### ISSUE THREAD

**Issue by pocketcasts** [Automattic/pocket-casts-ios#47]
**What the listener said:**

>Up Next won’t play next podcast in queue if connected to HomePod speakers. I can only listen to my queue if I don’t connect to speakers. Otherwise it stops after the currently playing episode.

>I’m connecting to my HomePod via Airplay. Pocketcasts is the only app that has this issue. Only the episode I actively press play will play. 

This has been happening for weeks with every podcast.

5253618-zen

**Comment by emilylaguna** [comment]
I was able to reproduce this using the following steps:

1. On your Mac, go to System Preferences > Sharing > Enable Airplay Receiver
   - This will allow your Mac to act as an Airplay speaker
2. On your device add many items to your up next
3. Tap the Airplay icon and select your Mac as the receiver
4. Play an episode
   - To speed things up you can skip to the last 20 seconds or so
6. Put the app in the background
13. Let the episode play out
14. 💥 When it finishes it will just stop playing.
