### ISSUE TITLE
Feature request: tap to go from the currently playing episode to page with all the episodes for a podcast

### ISSUE THREAD

**Issue by cfzlp** [Automattic/pocket-casts-ios#486]
From the list of podcast episodes in a Filter, it is possible to tap on an episode and then tap the name of the podcast to go that podcast's page, where all its episodes are.

But there is no obvious way to go the the list of episodes for the podcast for the currently playing episode.

I would like to be able to go from the "Now Playing" or the "Notes" tabs to the list of episodes of the podcast I am listening to.

Thank you.

**Comment by CookieyedCodes** [comment]
I use the go to podcast option from the customisable bottom bar 😉, the option is their just not the default 
 ![Screenshot_20221106-182148.jpg](https://user-images.githubusercontent.com/20846898/200188222-2d9eef24-6f70-40d7-b2d3-b731fbfd643c.jpg)

**Comment by cfzlp** [comment]
Ah! Got it! Thank you @CookieyedCodes. That solves it.
