### ISSUE TITLE
Feature Request: "Up Next" status as filter criteria

### ISSUE THREAD

**Issue by Bonney** [Automattic/pocket-casts-ios#493]
Similar to #451, it would be nice to have a filter option for is/is not in the "up next" queue. "All downloaded but not in my queue" is a filter list I find myself wanting. :)

**Comment by CookieyedCodes** [comment]
I would love this too 😋😋, just make sure it's cross platform 😉

**Comment by leandroalonso** [comment]
Heya @Bonney! Thanks for your request, I'm closing this Issue because feature requests/ideas should go to our  [Discussions](https://github.com/Automattic/pocket-casts-ios/discussions) section! Please feel free to open a topic there, thank you!
