### ISSUE TITLE
Edit folder screen has too many horizontal dividers

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-ios#53]
It looks to me like the Edit Folder screen has a lot of dividers. I think at least one of these could be removed (I'm looking at the two dividers between the colors and the delete button in particular), but I'm curious what @adamzelinski thinks.

![Screen Shot 2022-07-13 at 12 24 54 PM](https://user-images.githubusercontent.com/4656348/178783638-ae5e27b9-47f1-4013-9e10-97d83d4448a3.png)

**Comment by rviljoen** [comment]
@adamzelinski I had a look and the `ThemedDivider` is using the correct color:
https://github.com/Automattic/pocket-casts-ios/blob/1ed3c5b8353dcadc2cfd83fe86ca260ffe9baa99/podcasts/Styles.swift#L132-L137

It is missing padding though. Here is the current version:
![image](https://user-images.githubusercontent.com/25402814/206575212-b37de653-aa53-4c76-b80a-2f892a1f737e.png)

and then with padding of 10 applied:
![image](https://user-images.githubusercontent.com/25402814/206575273-b73ff57f-7385-4b27-9d47-4ae5175bcfcc.png)

Is 10 enough, or did you have a different value in mind?

**Comment by ghost** [comment]
The padding looks good to me thanks @rviljoen however I think the dividers need to be the width of the screen as it looks funny with the padding on either side

**Comment by rviljoen** [comment]
> The padding looks good to me thanks @rviljoen however I think the dividers need to be the width of the screen as it looks funny with the padding on either side

@adamzelinski Yes, I agree! I have removed the leading and trailing padding for the dividers:
![image](https://user-images.githubusercontent.com/25402814/206747374-075e0f0f-00fa-48a7-817e-f7463e56f3b8.png)

Let me know if this is good to go and I'll submit a PR.

**Comment by ghost** [comment]
the dividers look really great now thanks @rviljoen  however, now all the padding looks off. Can we please make sure all the text elements are in alignment. The padding from both edges should be 16pt.

<img width="522" alt="Screen Shot 2022-12-12 at 12 21 23 pm" src="https://user-images.githubusercontent.com/74938219/206942106-ce7c3261-8633-47d7-a434-332c9ea6ac35.png">

**Comment by rviljoen** [comment]
@adamzelinski Sorry, I missed that! Here's my latest attempt:

![image](https://user-images.githubusercontent.com/25402814/206996124-614d7081-5bb1-451f-8df4-b10ca21ed6ec.png)

In addition to fixing the padding, I also added some space between the Navigation Title ("Edit Folder") and the folder name to match your design.

**Comment by ghost** [comment]
Awesome, thanks @rviljoen that's looking great happy with that. I also assume that the close icon will be there too correct as it's not showing in your screenshots

**Comment by rviljoen** [comment]
@adamzelinski Yes, the close icon is visible in the app, but does not render in the Xcode view preview as it is not included in each individual view. Here is a render from the app on a real device, with the view controller rendering it:

![24A9CB7C-B596-4654-A165-2990A36FAC5A_1_201_a](https://user-images.githubusercontent.com/25402814/207264899-bde180b5-7647-4462-b5f5-61ebc3f953d3.jpeg)
