### ISSUE TITLE
Bulk unsubscribe options

### ISSUE THREAD

**Issue by tpeacock19** [Automattic/pocket-casts-ios#538]
I have an existing account that I would like to 'restart'. It has over 200 podcasts subscribed in it and I would like to remove all of them. I have only seen the option to unsubscribe when clicking into the podcast. Is there another option aside from clicking into 200+ podcasts individually?

**Comment by emilylaguna** [comment]
Hiya! We don't have a public way to unsubscribe to all podcasts yet. However if you are able to build the app there is an option in the developer menu to do so.

If not, you can reach out to support and ask them for help.

**Comment by tpeacock19** [comment]
Okay then, I'll build it locally. Is there anywhere for feature requests? It'd be great to just be able to select multiple podcasts to unsubscribe.

**Comment by leandroalonso** [comment]
Hi @tpeacock19! You can open a topic on our [Discussions](https://github.com/Automattic/pocket-casts-ios/discussions) section for feature requests. I'll convert this to a discussion.
