### ISSUE TITLE
Feature request: hide empty podcast on the main page

### ISSUE THREAD

**Issue by AKDub** [Automattic/pocket-casts-ios#539]
Much like the ability to hide played/archived episode in the episode list, it would be nice to be able to do the same with the podcasts themselves.

It’s a small touch but I’m sure there would be others that would enjoy the cleaner look.

**Comment by CookieyedCodes** [comment]
Or at the very least have them automatically go into a spefic folder 🤔 😉

**Comment by leandroalonso** [comment]
Heya @AKDub ! Thanks for your request, I'm closing this Issue because feature requests/ideas should go to our  [Discussions](https://github.com/Automattic/pocket-casts-ios/discussions) section! If you're still interested please feel free to create a topic there.
