### ISSUE TITLE
Requires detailed deployment documentation

### ISSUE THREAD

**Issue by jiangdi0924** [Automattic/pocket-casts-ios#546]
I tried to deploy the development environment locally，but got into a lot of trouble.  hope the contributor can add a detailed description how to build a project locally.  like the [pocket casts android repo](https://github.com/Automattic/pocket-casts-android)  was easy to understand

### Expected behavior
local build this project

### Actual behavior
lots of error, like fastlane error , Build input file cannot be found: '/Users/XXX/Library/Developer/Xcode/DerivedData/podcasts-bmafskcmzwyvjhacdzaecwjasxmy/Build/Products/DerivedSources/GoogleService-Info.plist'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? error

##### Tested on [device], iOS [version], Pocket Casts [version]
iOS

**Comment by rviljoen** [comment]
I was able to build using only the instructions in 'README.md'. Are you seeing any errors when running the two 'make' commands? Those commands should set up all dependencies. 

![image](https://user-images.githubusercontent.com/25402814/204140357-71571b8d-189d-4fc2-8481-d4873a94079d.jpeg)

**Comment by jiangdi0924** [comment]
Thank you for your reply
After  `make external_contributor`

Xcode start app with simulator reprot error
![image](https://user-images.githubusercontent.com/21988177/204712420-58b71f03-774a-48b2-ac24-9e8975c83a88.png)
I am now a little confused, In which directory do I need to execute `bundle exec fastlane run configure_apply`.When I run this command from the root of the project I get the following error:
![image](https://user-images.githubusercontent.com/21988177/204807699-54868ea1-a517-482f-a66c-b88cee75c32d.png)

finally...  after to deleted some files and target, it worked on my simulator, hope you can describe the document in detail，very appreciated.

<img width="359" alt="image" src="https://user-images.githubusercontent.com/21988177/204822772-5c440c19-84ed-4cb0-a3af-978b8a3dcc6d.png">










### Env
* Xcode 14.1
* macOS m1 13.0 
*  Bundler version 2.3.23 (2022-10-05 commit 250d9d485d)
*  ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [arm64-darwin22]
