### ISSUE TITLE
Lockscreen: Allow the customization of actions shown

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-ios#551]
### Expected behavior

Allow users to customize if they want scrubbing, the skip forward and skip backwards buttons displayed

### Actual behavior

All of those actions are displayed with no option to hide/remove them. This can lead to accidentally pressing the buttons

<img width="424" alt="image" src="https://user-images.githubusercontent.com/16253818/204472548-02a3b38e-9627-4957-a10f-5d0f6460c492.png">

**Comment by rviljoen** [comment]
I don't believe these requested customizations are possible. The Now Playing widget is a standard Apple OS component and apps do not have any control over layout and formatting:

> You do not have direct control over which information is displayed, or its formatting. You set the values of the now playing info center dictionary according to the information you want to provide to the system. The system, or the connected accessory, handles the information’s display in a consistent manner for all apps.

More information in the [official documentation](https://developer.apple.com/documentation/mediaplayer/mpnowplayinginfocenter).

When Apple announced [Live Activities](https://developer.apple.com/documentation/activitykit/displaying-live-data-with-live-activities) earlier this year I thought it may create a mechanism for audio apps to customize the lock screen player experience, but after reading up about it a bit I don't think this is the intended use case.

**Comment by joashrajin** [comment]
Thanks for that, @rviljoen 😀

I'll go ahead and close this for now, but if Apple decides to add more customization options we can re-open it 👍

**Comment by zealot128** [comment]
2 years later, still no sign from Apple :( - That's a bummer!
More than a couple of times I lost my play position while having the phone in a pocket, grabbing it with one hand, and one finger accidentally scrubbed back to the beginning or end or so.
Especially enraging when it is one of those very long podcasts (3-5h) without any chapter marks.

How does live streaming apps, radio stations and such handle this? They obviously do not allow skipping or scrubbing by nature of the medium? Is it possible to use the same API's or is it a different concept in the iOS-API.

**Comment by rviljoen** [comment]
@zealot128 It is possible to disable the scrubber. That option is coming soon! https://github.com/Automattic/pocket-casts-ios/issues/2200

**Comment by zealot128** [comment]
> [@zealot128](https://github.com/zealot128) It is possible to disable the scrubber. That option is coming soon! [#2200](https://github.com/Automattic/pocket-casts-ios/issues/2200)

Wow, that's great news! Always look forward to PC releases :)
