### ISSUE TITLE
Possible battery drain issues on iOS 16.2

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-ios#583]
We've received a report of a significant increase in battery drain on a device using iOS 16.2. The user also mentioned the phone getting quite hot. 

> Usually I can listen for 2-3 hrs with the percentage going down 10-15% now it’s gone down 33% in 2,5 hrs. With 41% of my total power draw while phonescreen of. 

Since this iOS version is still in the beta stage, I think it could be an iOS bug in the beta but reporting it here so we can keep an eye

**Comment by rviljoen** [comment]
@joashrajin Have you received any similar reports? I have not seen this at all, either on 16.2 beta or the released version.

**Comment by joashrajin** [comment]
@rviljoen we haven't gotten any new reports, so this might have been a bug on the iOS beta. I will close this for now :)
