### ISSUE TITLE
Selecting Episode in CarPlay Does Not Go to Player Screen

### ISSUE THREAD

**Issue by hubmacfan** [Automattic/pocket-casts-ios#592]
### Expected behavior
When in CarPlay, if one presses on an episode of a podcast, the player screen should open and the podcast begin playing

### Actual behavior
The podcast begins playing, but it stays on the list of episodes. See attached video.

https://user-images.githubusercontent.com/14169031/206739877-47339728-da30-49df-aeec-6ff91a54970e.mp4

### Steps to reproduce the behavior
Select an episode to play, from either a playlist or a particular podcast

##### Tested on [device], iOS [version], Pocket Casts [version]
iPhone 12, iOS 16.1.2, PC 7.27 (in case the car makes a difference, 2020 Kia Optima)

**Comment by pjolt** [comment]
I see the same behavior. I am a new user to PC and how this currently works feels unintuitive to me since I expect to get the Now Playing screen automatically when I start playback and not having to manually switch to it. 

iPhone 13 Pro, IOS 16.2, PC 7.28.1
