### ISSUE TITLE
iOS 16: issue with Spatial Audio

### ISSUE THREAD

**Issue by pocketcasts** [Automattic/pocket-casts-ios#62]
The app has issues playing podcasts when Spatial Audio is enabled when using the `EffectsPlayer`.

While this does seem to be an issue (or at least a change) on Apple's side, other apps don't have the same behavior, so it's better to look at it to avoid having this issue when iOS 16 is released.

### Steps to reproduce the behavior

You'll need to test that on a real device with iOS 16 beta + AirPods Pro (or Max). 

1. Play any podcast on PocketCasts
2. Swipe down to show the control center
3. Tap and hold on your volume settings
4. Tap "Spatialize Stereo"
5. Tap Fixed or Head Tracked
6. Search for the podcast "The Rizzuto Show"
7. Download an episode
8. Try to play it
9. You'll see that the playback won't start

(A few times it might be that this work, just kill and reopen the app and try again).

### #5280245-zen

User reports that they are having occasional issues with episodes not playing when listening through AirPods, even when the episode is downloaded.

- Spotify, Apple Podcasts, and Apple Music have no problems so far
- Episodes play just fine through phone speakers
- The user highlighted how all but three episodes in their Up Next queue could not be played:

<details><summary>Screenshot</summary>

![IMG_2326](https://user-images.githubusercontent.com/74066241/172800716-67a2a857-cf5b-4b17-9b56-5e9b30a8707a.PNG)

</details>

- App Version: 7.19.3
- Device: iPhone12,5
- OS: 16.0

**Comment by erricgunawan** [comment]
Possibly related/same issue (although some conditions look different):

> I feel like this is related to new iOS. I push play and after second it stops. I deleted the app and reloaded it and still happening. If I reboot my phone it fixes the problem. I am on version 16.02

> Happens on all locations.
Literally plays for less than a second then stops. Reboot fixes it.
This is also happening with Spotify in the same way.

> No VPNs.
When it happens it does happen for every podcast. Once it happens it seems like only one out of it is to reboot my phone. Yesterday I reset my network settings. It only started happening after iOS 16.
It happens regardless of listening mode.
When it happens I have tried going only wireless or only cellular and still happens.

> App Version: 7.23
Device: iPhone12,1
OS: 16.0.2

5609802-zen
