### ISSUE TITLE
Apple Shortcut not importing some podcasts

### ISSUE THREAD

**Issue by kub1x** [Automattic/pocket-casts-ios#632]
### Expected behavior
Apple Shortcut should import all podcasts in Apple Podcasts. 

### Actual behavior
When podcast don't have a Store URL set, it is not exported. 

### Steps to reproduce the behavior
Subscribe to "Getting to Yes, and" podcast in Apple Podcasts app, see link to the podcast here: https://www.secondcityworks.com/podcast
Run the "Apple Podcasts to PocketCasts" Shortcut. 
The PocketCasts app won't import the podcast (and complain about incorrect OPML file format as there were no exported podcasts). 

##### Tested on iPhone SE 2020, iOS 16.2, Pocket Casts 7.28.1.0

The shortcut produces export file without this podcast, as it has no Store URL specified. 
When I edited the Shortcut so that it exports the Feed URL instead in case there is no Store URL specified, it transferred the podcast correctly. See image of the edit below. It looks that PocketCasts is able to import the apple podcasts url as Feed URL. I still don't understand why the "Getting to Yes, and" podcast isn't in PocketCast registry already and am not sure how to add it (other than through Apple Podcasts, which is why I got here). 

I'm not sure how to properly commit the edited binary Shortcut file here, but the edit is pretty straightforward: 

<img width="876" alt="Screenshot 2023-01-10 at 15 43 51" src="https://user-images.githubusercontent.com/1833840/211582505-492f7e73-aca7-4388-8a22-2968313bf353.png">

Exported file before the edit: 
[apple-podcasts-export.opml.txt](https://github.com/Automattic/pocket-casts-ios/files/10383727/apple-podcasts-export.opml.txt)

Exported file after the edit: 
[apple-podcasts-export-2.opml.txt](https://github.com/Automattic/pocket-casts-ios/files/10383733/apple-podcasts-export-2.opml.txt)

Thanks, 
Jakub

**Comment by joashrajin** [comment]
5832352-zd-woothemes
