### ISSUE TITLE
CarPlay: crash reports on iOS 15.4

### ISSUE THREAD

**Issue by pocketcasts** [Automattic/pocket-casts-ios#64]
Original report in Slack: p1647503453744539-slack-C02A333D8LQ

TL;DR: Pocket Casts app crashes on CarPlay after updating iOS to 15.4

> When I click on the icon, the area on the screen where the app should be is blank. It stays like that for a few seconds and then goes back to the main screen of CarPlay.

**List of tickets so far**

* #4865900-zen
* #4873212-zen
* #4898932-zen

One of the users tried with Airplane mode and reported it is still happening:

> I fiddled around with airplane mode again this morning, and I managed to get the app working in CarPlay for 1 hour / 2 connections. Then it started crashing again, and I couldn’t get it to work again.

**Comment by erricgunawan** [comment]
Same user from [two posts above](https://github.com/Automattic/pocket-casts-ios/issues/64#issuecomment-1205964022):

> The crashing of the app in CarPlay is back after it was fixed with the new iOS. Everything worked and it was fine when I updated in September.
>
> Now before the annual busiest travel day in the states, Pocket Casts is back to crashing when I attempt to open it in CarPlay.

UPDATE (after asking if they already tried Beta): 

> Yes, I ran the beta for a while but stopped because my Apple watch wasn’t syncing properly.

> It did crash in the beta builds as well. As I mentioned earlier the only time it didn’t was after I updated to iOS 16.

5718024-zen

App Version: 7.26
Device: iPhone13,3
OS: 16.1.1

**Comment by thabotswana** [comment]
>Within the Pocket Cast App, if I'm in one of the filters with several podcasts, it will stop me from being able to scroll down, constantly trying to scroll back to the top podcast.
>
>This goes on for about 1-3 minutes until the whole app shuts down and brings me to the CarPlay homescreen. Then the app works fine. It doesn't crash the whole CarPlay interface, it simply closes the Pocket Casts app.
>
>It usually only happens if I start playing a podcast using CarPlay. If I start playing the podcast on the iPhone app and connect to the car, no error occurs.

5835847-zen

App Version: 7.28.1
Device: iPhone12,5
OS: 16.0
