### ISSUE TITLE
Add option to change which podcasts trigger app badge

### ISSUE THREAD

**Issue by dartiss** [Automattic/pocket-casts-ios#642]
So, this is different to the numeric badges on the podcast icons - I'm referring to the "new podcasts" badge that you get against the Pocket Casts app on the home screen.

I'd like a way to specify which podcasts this badge counts.

Why? In my case I have some podcasts which are more important to me than others, and I really only want to know when any of them get new episodes.

**Comment by dartiss** [comment]
This is a spin-off from #634, which is about the confusion over the settings references to badges and what they control (podcast or app badge).

**Comment by leandroalonso** [comment]
Hey @dartiss, I'm converting this issue to a discussion given it's a feature suggestion.
