### ISSUE TITLE
Skip control on lock screen shows "-"

### ISSUE THREAD

**Issue by reginabally** [Automattic/pocket-casts-ios#658]
### Expected behavior
I expect the skip control in the lock screen matches my settings at Profile > Settings > General.

### Actual behavior
The mini-player shows a "-" for the skip-back control on the lock screen. The issue was originally reported in this [Tweet](https://twitter.com/jackjohnbrown/status/1616218933429952512).

### Steps to reproduce the behavior
1. Go to Profile > Settings > General, and change the skip-back duration to 25 seconds.
2. Play a podcast without custom skip controls
3. Lock the phone
4. Check the lock screen and notice the skip back control shows up as "-"

### Screenshots

Skip back control in the app:

![IMG_F98F7A5C13FB-1](https://user-images.githubusercontent.com/40906847/213610785-81fa2159-b11b-4f14-b031-645f3c17d152.jpeg)

Skip back control on the lock screen:

![IMG_777F8F11862A-1](https://user-images.githubusercontent.com/40906847/213610804-2192fe3f-5f35-4337-834b-b80d1b3e8a08.jpeg)

**Comment by rviljoen** [comment]
Hi @reginabally - the skip buttons in the app are rendered by the app itself, so we have full control over what is displayed and hence we can show back as 25 (as per the screenshot). The Now Playing widgets (both lock screen and control centre) are rendered by iOS and we do not have full control over what is rendered. We can provide iOS with any number for skip back or forward, but the widget will only render the actual number if it is 5,10,15,30,45,60,75 or 90. Any other value will be rendered as - or +. The button does skip the correct amount though, as the user correctly pointed out.

**Comment by reginabally** [comment]
Thank you so much for clarifying, @rviljoen! Closing this issue since this is expected.
