### ISSUE TITLE
Auto Add to Up Next: All change "To Bottom" in some cases

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-ios#712]
### Expected behavior

Your custom "To Top" setting should remain intact

### Actual behavior

They all are reset to "To Bottom"

### Steps to reproduce the behavior

Initially, it was a bit tricky to replicate, but here is what I did: 

- Under 'xxxx' Podcasts Chosen, selected all podcasts
- Deselected the first podcast
- Went back to the 'Auto Add Podcasts' page, and set a few of them to use "To Top"
- Switched back to the 'xxxx' Podcasts Chosen page, and selected the first podcast
- Upon going back, all of the podcasts were now using the "To Bottom" option 

Recording of how to replicate: 

https://user-images.githubusercontent.com/16253818/218732707-eedf8b69-b57d-4755-a33c-3589abd47aa4.MP4

##### Tested on [iPhone 14 Pro Max], iOS [16.3], Pocket Casts [7.32]

5945768-zd-woothemes

**Comment by igotdes** [comment]
Reported in #6383536-zen:

> [...] when new episodes download and are adding to playback queue it pushes existing episodes in the queue randomly to other spots sometimes in middle of queue sometimes at the end.
