### ISSUE TITLE
Podcast New Episode Notification Not Firing

### ISSUE THREAD

**Issue by azollafox** [Automattic/pocket-casts-ios#713]
### Expected behavior
When I have notifications for specific podcasts enabled, I should get a notification on my device when Pocket Casts sees there's a new episode

### Actual behavior
Since 7.29 and through 7.31 we have seen reports of missing notifications

### Steps to reproduce the behavior
Unclear. @joashrajin has seen it in action on his device though 

##### Reported on
iPhone12.1, iOS 16.3, Pocket Casts 7.31 5951313-zen
iPhone12.1, iOS: 16.0 Pocket Casts 7.29 5874759-zen

**Comment by leandroalonso** [comment]
I experienced that myself last week too.

@geekygecko @srjakes do we have any logs for Push Notifications we can look at?

**Comment by rviljoen** [comment]
I have noticed something similar, but in my case notifications were not being sent at all. Disabling and re-enabling them in the app had no effect. I had to uninstall and re-install the app and then the issue was resolved.

**Comment by thabotswana** [comment]
Another report in 5968683-zen

>Notifications stopped working for me Sunday afternoon and since then I have not received any on my iPad. Things continue to work on my iPhone.

App Version: 7.31
Device: iPad14,6
OS: 16.3.1

**Comment by rviljoen** [comment]
Could be related to #1198

**Comment by joashrajin** [comment]
> Could be related to #1198

AFAIK, this bug report was related to a server issue and was fixed. I agree that all of the newer cases are related to the migration issue. 

I'll mark this as closed for now.
