### ISSUE TITLE
Project: Bookmarks

### ISSUE THREAD

**Issue by emilylaguna** [Automattic/pocket-casts-ios#717]
### Setup

- [x] Add feature flag: https://github.com/Automattic/pocket-casts-ios/pull/718
- [x] Create a new table in the database: https://github.com/Automattic/pocket-casts-ios/pull/718
- [ ] Add a data manager that:
   - [ ] Adds new bookmarks: https://github.com/Automattic/pocket-casts-ios/pull/719
   - [ ] Retrieves bookmarks: https://github.com/Automattic/pocket-casts-ios/pull/719
   - [ ] Deletes bookmarks
   - [ ] Updates bookmarks

### Adding Bookmarks

- [ ] Add a way to add via the Player: https://github.com/Automattic/pocket-casts-ios/pull/720
- [ ] Add a way to add via headphones
- [ ] Add a way to add via Siri
- [ ] Add a way to add via CarPlay
- [ ] Add a way to add via the Watch App
- [ ] Add a sound notification when the user creates a bookmark via the headphone gesture: https://github.com/Automattic/pocket-casts-ios/pull/720

### Viewing Bookmarks
- [ ] Add a way to view a list of the bookmarks from the player
- [ ] Add a way to view a list of the bookmarks on the profile tab
- [ ] Add a tap handler to play the episode from the bookmarked timestamp
- [ ] Show a visual indicator on the player timeline of where a bookmark is

### Managing Bookmarks
- [ ] Add a way to delete bookmarks
- [ ] Add a new settings section to control how bookmarks work (headphone gesture, length?, etc)

### Education
- [ ] Add a method of informing the user of the new feature, and educating the user on how to create bookmarks using the various methods
- [ ] Add a sound clip that educates the user when if they make a bookmark using a non-visual method (headphones, Siri, etc) for the first time

### Final touches

- [ ] Analytics
- [ ] iPad Testing
- [ ] iOS 14 Testing

**Comment by BKrnk1337** [comment]
This project sounds Promising
