### ISSUE TITLE
Audio is no longer pausing during phone calls

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-ios#735]
### Expected behavior

The playback should pause during a call and resume once the call has ended. Seems to have started in v7.32

### Actual behavior

The playback continues while you're on a call. We may need to also look into how it works in CarPlay

### Steps to reproduce the behavior

- Play an episode
- Accept a phone call on the device playing the audio
- The podcast will continue playing while on the call

##### Tested on [iPhone 14 Pro Max], iOS [16.3], Pocket Casts [7.33]

5984411-zd-woothemes

**Comment by joashrajin** [comment]
5983106-zd-woothemes

> In this new app release when I start a call listening a podcast the play start again over the call. Further connected to CarPlay the playback start again after paused it !

**Comment by joashrajin** [comment]
5985091-zd-woothemes

> while using your app playing podcast and my phone starts ringing audio doesn’t stop playing and can hear audio from phone and podcast at the same time

**Comment by joashrajin** [comment]
5979352-zd-woothemes

**Comment by joashrajin** [comment]
5986124-zd-woothemes

**Comment by joashrajin** [comment]
5987989-zd-woothemes

**Comment by joashrajin** [comment]
5988205-zd-woothemes

**Comment by joashrajin** [comment]
5993556-zd-woothemes

**Comment by joashrajin** [comment]
5997139-zd-woothemes

**Comment by joashrajin** [comment]
5994588-zd-woothemes

**Comment by joashrajin** [comment]
5994865-zd-woothemes

**Comment by emilylaguna** [comment]
Closing as this has been fixed via: https://github.com/Automattic/pocket-casts-ios/pull/739 and released in 7.32.1.
