### ISSUE TITLE
App Icon: setting Rosé as the app icon doesn't display it on the Now Playing widget

### ISSUE THREAD

**Issue by leandroalonso** [Automattic/pocket-casts-ios#747]
### Expected behavior

When setting the Rosé custom icon it should reflect on our widget.

### Actual behavior

The icon doesn't appear.

| Rosé | Normal |
| ---- | -------- |
| ![2  RoseIcon](https://user-images.githubusercontent.com/7040243/221939481-6c455cd2-c4c9-48ab-9039-ed10b384c39f.jpg) | ![1  ClassicIcon](https://user-images.githubusercontent.com/7040243/221939507-867d0469-6cab-437a-ba55-0397580b2a05.jpg) |

### Steps to reproduce the behavior

1. Add the Now Playing widget to your screen
2. Clean your Up Next queue and now playing item
3. Change icon to Rosé
4. Check that nothing appears on the widget

**Comment by leandroalonso** [comment]
@adamziel any chance you can help us with having the Rosé icon in 60x60 @ 3x?

**Comment by leandroalonso** [comment]
@adamzelinski can you help us with having the Rosé icon file for 60x60@3x? Thanks!

**Comment by ghost** [comment]
Here is the icon @leandroalonso 
![AppIcon-Round-Pink@3x](https://user-images.githubusercontent.com/74938219/222011603-c31908bf-6fc8-476b-95ec-c61223af5ce8.png)

**Comment by yaelirub** [comment]
Hey @leandroalonso , I wanted to work on this PR, but I am seeing the file 🤔 
https://github.com/Automattic/pocket-casts-ios/blob/trunk/podcasts/AppIcon-Round-Pink60x60%403x.png

**Comment by leandroalonso** [comment]
@yaelirub somehow I missed the file when double-checking 🤔 

But there's def an issue with one of the icon sizes for Rosé, I'll update the ticket description.

**Comment by mdrockwell** [comment]
Another user is experiencing this in 6082180-zd-woothemes
