### ISSUE TITLE
Exclude downloads from backups

### ISSUE THREAD

**Issue by ropery** [Automattic/pocket-casts-ios#792]
I would like to exclude downloaded media files from being backed up to iCloud, while keeping settings &c. Please add a setting for that, thanks.

**Comment by rviljoen** [comment]
Not able to reproduce this. My app storage use is 3.5GB but my iCloud backup is only 64MB. Needs further investigation.

**Comment by ropery** [comment]
True. Looks like you're right. I don't remember if it was different when I filed the issue, possibly out of misunderstanding. Could anyone familiar with the code confirm, that downloaded media files are never sent to iCloud for backup? (--Then, I could also see someone wanting to include them, but that's another story.)

**Comment by rviljoen** [comment]
Hey @ropery - I had a quick look, and the episode folders are indeed set to not backup:

https://github.com/Automattic/pocket-casts-ios/blob/04a99074963bc927f17d3eca6d6ee324e3c95cf5/podcasts/DownloadManager.swift#L91-L98

https://github.com/Automattic/pocket-casts-ios/blob/04a99074963bc927f17d3eca6d6ee324e3c95cf5/podcasts/SJCommonUtils.m#L23-L30

**Comment by ropery** [comment]
Right. Happy to close this issue now. Thank you!
