### ISSUE TITLE
Sign in with Apple and Google buttons don't register taps properly

### ISSUE THREAD

**Issue by rustyshelf** [Automattic/pocket-casts-ios#835]
### Expected behavior
- Entire button should be tappable

### Actual behavior
- Buttons are only tappable on the portion that contains text or an icon. Tapping the blank portions inside the border does nothing.

### Steps to reproduce the behavior
- try to tap the button inside the button border, but on the right hand side where there's no text, or in the portion between the icon and the text:
![IMG_F6F368EB1F7F-1](https://user-images.githubusercontent.com/610217/234446549-1899c651-7e7f-4b33-82be-7b183dbed775.jpeg)

##### Tested on iPhone 14 Pro, iOS 16.4.1, Pocket Casts 7.37.0.0

**Comment by emilylaguna** [comment]
Nice catch @rustyshelf! It's been fixed in this PR and will be available in the next beta for the 7.37 release: https://github.com/Automattic/pocket-casts-ios/pull/837
