### ISSUE TITLE
An episode can't be played when downloaded, but will play when streamed.

### ISSUE THREAD

**Issue by emilylaguna** [Automattic/pocket-casts-ios#900]
Related: https://github.com/Automattic/pocket-casts-ios/issues/898

As of right now I have only been able to reproduce this with this single episode: https://pca.st/22iph0yt

The episode https://pca.st/22iph0yt is able to be streamed, but when after downloading it the player will not be able to play it and will instead result in the episode ceasing to play.

### Expected behavior

The episode will either play, or an error message should be shown.

### Actual behavior

The episode just stops playing or is archived if the setting is enabled.

### Steps to reproduce the behavior

1. Go to episode https://pca.st/22iph0yt
2. Play it to start streaming
3. ✅ Verify the episode plays
4. Download the episode
6. Play it
7. 💥 The episode will stop playing

**Comment by emilylaguna** [comment]
I did some investigating to figure out what is causing this to happen, and how we might be able to fix it. 

### What's going on?

Ultimately what is happening is there is some corruption in the downloaded episode that is causing the EffectsPlayer to not be able to play it due to an issue internally with the `AVAudioFile`. The error that is being shown is:

```
Packet with multiple raw data blocks was found: unsupported
```

### Why does it play if I play it on the web player?

It turns out there are dynamic ads in the episode and when you download it on the web or elsewhere you end up with a version of the episode with no issues at all, but when downloading on mobile you end up with a file with some minor corruption. 

You can see the file size difference here:
<img width="456" src="https://github.com/Automattic/pocket-casts-ios/assets/793774/27ced267-e9a0-4fb7-bd41-3932d66f02b2">

### Why are we able to stream the episode without any issues?

When we stream a file we use the `DefaultPlayer` which uses the simple `AVPlayer` under the hood which for some reason doesn't have this bug, so the file will play correctly. 

The AVPlayer is also what Apple Podcasts, and other apps use for their standard players which is why this appears not to happen to them.

I have also confirmed this issue exists outside of Pocket Casts by using a [sample project](https://developer.apple.com/documentation/avfaudio/audio_engine/playing_custom_audio_with_your_own_player) from Apple.

### What's the fix?

Unfortunately since this is an issue with the file and an internal issue with AVFoundation there isn't anything we can do directly to fix this. However we can improve how we handle this and similar issues:

#### 1. When playing a file using the EffectsPlayer, verify the file was loaded correctly.

Right now we rely on an [exception being thrown](https://github.com/Automattic/pocket-casts-ios/blob/0bfcd809e216864989ce78181947ea89ac39052a/podcasts/EffectsPlayer.swift#L105) when trying to load the audio file data to determine if it was loaded correctly. 

However we can detect whether the file was loaded [correctly by checking](https://gist.githubusercontent.com/emilylaguna/72286e3326b6678750608aba28d6632c/raw/b94e0e10a663f7e8f60f2ad2d6705ce817a79b2b/EffectsPlayerLengthCheck.swift) if the  `AVAudioFile.length` value is still 0 after trying to load it.

This will cause the player to fail, but the experience is still less than optimal. 

#### 2. Use the DefaultPlayer as a fallback

Since we know the DefaultPlayer (AVPlayer) plays this file correctly, we could detect when the EffectsPlayer has an error and then fallback to the DefaultPlayer.

While this seems simple, unfortunately there are some complexities in this instance:

- The file is an AAC audio file
- When we download an AAC file, we assign it with the file extension [`m4a`](https://github.com/Automattic/pocket-casts-ios/blob/0bfcd809e216864989ce78181947ea89ac39052a/podcasts/FileTypeUtil.swift#L16)
- The file extension is what AVFoundation uses to determine what kind of file its playing
- When the AVPlayer attempts to play the AAC file it thinks it's an m4a and it fails to play it because its an unexpected type

If we change the extension from `m4a` to `aac` the file plays correctly. But, now we hit the next complexity, which is all of the downloaded file paths are determined at runtime, which means if we change to `aac` and a user updates their app, any AAC files they have downloaded will no longer appear, and will be ghosted in the downloads forever.

We'll need to come up with a transition strategy so we don't affect anyones downloads, an idea could be:
- Add a way to query for episodes with a specific `fileType`, in this case `audio/aac`
- When the app is updated, perform a one-time process of:
   - Querying for all aac files
   - Get the download URL for it, which will be the one with aac
   - Replace aac with m4a
   - Move the old m4a file to an aac file

#### 3. Use the DefaultPlayer as a fallback part 2

If we fix the aac file mapping, and add the EffectsPlayer error handling we can then add a way to fallback to the DefaultPlayer if for some reason the EffectsPlayer fails. 

The good news is that we already have code to switch between players since that's how we handle AirPlay and casting. In theory we could detect when the playback fails from the EffectsPlayer, then add a flag to the PlaybackManager to use the `DefaultPlayer`, and then call the code to switch players again. 


### Conclusions
- Ultimately this is an issue with a corrupted file and an internal bug from Apple.
- While we can't fix the core issue, we can improve our handling of playback errors by:
   - Using aac for the downloaded file type
   - Add EffectsPlayer playback failure handling to fallback to the DefaultPlayer which doesn't have this issue.

**Comment by rviljoen** [comment]
@emilylaguna I've not gone through all the details, but I've noticed that https://github.com/Automattic/pocket-casts-ios/issues/843 reported on the watch is from the same podcast. These issues may be related?

**Comment by joashrajin** [comment]
+1 in 6478878-zd-woothemes

In this case, the error is occurring on https://pca.st/XjHa

**Comment by joashrajin** [comment]
+1 in 6725992-zd-a8c

Error seems to be occurring with https://pca.st/y3erphjx

**Comment by joashrajin** [comment]
7099707-zd-a8c

**Comment by alevarsir** [comment]
Another instance of this at https://twitter.com/dagronf/status/1755484992317403526

**Comment by joashrajin** [comment]
7794309-zd-a8c

**Comment by joashrajin** [comment]
7927125-zd-a8c

**Comment by SergioEstevao** [comment]
I was running some tests with this podcasts: [https://pca.st/lxQlTJ](https://pca.st/lxQlTJ) and I'm finding that for this case the files for the podcast are stated as `mp3` files. When downloaded as mp3 and trying to playing it they fail, but if we rename them to `m4a` they work correctly.

I was thinking could we have a mechanism that we use when a file fails to play in a format, were we move the file to to another format and see if it works: something like `mp3 -> m4a` or the other way around `m4a -> mp3` because it looks this can easily happen.

**Comment by leandroalonso** [comment]
> I was thinking could we have a mechanism that we use when a file fails to play in a format, were we move the file to to another format and see if it works: something like mp3 -> m4a or the other way around m4a -> mp3 because it looks this can easily happen.

This looks like an interesting idea!

**Comment by SergioEstevao** [comment]
I dig a further more and found another solution, when we download the files from the server, the server returns a content type header, for the example file I used it actually returns the file type: `audio/x-m4a` that is the real file type for the file.

The sad thing is that AVAsset on iOS instead of looking at the file metadata it basically only looks at the file extension to assess the file type.

So while the podcast rss file says that it's an mp3 in reality it's a m4a. ( I imagine this could also happen when ad servers change files on the fly)

I was thinking that we could had a new field on episodes, so that we record the server file type returned when we downloaded the file, and use that type to set the extension instead of the one announced by the podcast rss file.

**Comment by SergioEstevao** [comment]
So to add a bit more complexity:

- EffectsPlayer manages to play files even if the extension that they have mismatch with the real content format
- DefaultPlayer only plays correctly if the file extension matches the real content format
